/**
 * Mock chat data for testing
 * In production, this would come from API/backend
 * Chat list should only contain metadata, not all messages
 * 
 * Key optimization: Separate chat list from messages to handle huge data
 */

/**
 * Available students/contacts for starting new chats
 * These appear in Add Modal but NOT in chat history until a chat is started
 */
export const availableStudents = [
  {
    id: 'student1',
    name: 'Alex Johnson',
    role: 'Student - Grade 10A',
    type: 'direct',
    initials: 'AJ',
  },
  {
    id: 'student2',
    name: 'Emma Wilson',
    role: 'Student - Grade 10B',
    type: 'direct',
    initials: 'EW',
  },
  {
    id: 'student3',
    name: 'Liam Brown',
    role: 'Student - Grade 11A',
    type: 'direct',
    initials: 'LB',
  },
  {
    id: 'student4',
    name: 'Sophia Davis',
    role: 'Student - Grade 11B',
    type: 'direct',
    initials: 'SD',
  },
  {
    id: 'student5',
    name: 'Noah Anderson',
    role: 'Student - Grade 12A',
    type: 'direct',
    initials: 'NA',
  },
  {
    id: 'student6',
    name: 'Olivia Martinez',
    role: 'Student - Grade 12B',
    type: 'direct',
    initials: 'OM',
  },
  {
    id: 'student7',
    name: 'Ethan Taylor',
    role: 'Student - Grade 9A',
    type: 'direct',
    initials: 'ET',
  },
  {
    id: 'student8',
    name: 'Ava Thomas',
    role: 'Student - Grade 9B',
    type: 'direct',
    initials: 'AT',
  },
  {
    id: 'student9',
    name: 'Mason Garcia',
    role: 'Student - Grade 10A',
    type: 'direct',
    initials: 'MG',
  },
  {
    id: 'student10',
    name: 'Isabella Lopez',
    role: 'Student - Grade 10B',
    type: 'direct',
    initials: 'IL',
  },
  {
    id: 'student11',
    name: 'Lucas White',
    role: 'Student - Grade 11A',
    type: 'direct',
    initials: 'LW',
  },
  {
    id: 'student12',
    name: 'Mia Harris',
    role: 'Student - Grade 11B',
    type: 'direct',
    initials: 'MH',
  },
];

export const chatData = [
  {
    id: 'chat1',
    name: 'James Torff',
    role: 'Parent',
    type: 'direct',
    isGroup: false,
    initials: 'JT',
    lastMessage: "We're thinking of a new class project...",
    lastMessageSender: 'me', // Last message was sent by current user
    unread: 0,
    time: '09:14 AM',
    timestamp: '2025-11-14T09:14:00Z',
    avatar: '',
    messageCount: 2,
    status: 'delivered',
    isOnline: true,
  },
  {
    id: 'chat2',
    name: 'Designer Bros',
    type: 'group',
    isGroup: true,
    initials: 'DB',
    members: 6,
    lastMessage: 'Yeah. I took a quick look!',
    lastMessageSender: 'me', // Last message was sent by current user
    unread: 0,
    time: 'Yesterday',
    timestamp: '2025-11-13T15:30:00Z',
    avatar: '',
    messageCount: 2,
    status: 'sent',
  },
  {
    id: 'chat3',
    name: 'Computer Lab Group',
    type: 'group',
    isGroup: true,
    initials: 'CL',
    members: 8,
    lastMessage: 'Bring your project files.',
    lastMessageSender: 'other', // Last message was received
    unread: 0,
    time: 'Yesterday',
    timestamp: '2025-11-13T14:00:00Z',
    avatar: '',
    messageCount: 0,
    status: 'read',
  },
  {
    id: 'chat4',
    name: 'Giana Donin',
    role: 'English Teacher',
    type: 'direct',
    isGroup: false,
    initials: 'GD',
    lastMessage: 'Friday is perfect! Really excited to see what you come up with.',
    lastMessageSender: 'other', // Last message was received
    unread: 0,
    time: '09:45 AM',
    timestamp: '2025-11-14T09:45:00Z',
    avatar: '',
    messageCount: 7,
    status: 'read',
    isOnline: true,
  },
  {
    id: 'chat5',
    name: 'Sarah Martinez',
    role: 'Math Teacher',
    type: 'direct',
    isGroup: false,
    initials: 'SM',
    lastMessage: 'Can we schedule a meeting for next week?',
    lastMessageSender: 'other', // Last message was received
    unread: 3,
    time: '08:30 AM',
    timestamp: '2025-11-14T08:30:00Z',
    avatar: '',
    messageCount: 5,
    status: 'sent',
    isOnline: false,
  },
  {
    id: 'chat6',
    name: 'Science Club',
    type: 'group',
    isGroup: true,
    initials: 'SC',
    members: 12,
    lastMessage: 'Meeting postponed to Thursday',
    lastMessageSender: 'other', // Last message was received
    unread: 0,
    time: '2 days ago',
    timestamp: '2025-11-12T16:00:00Z',
    avatar: '',
    messageCount: 8,
    status: 'read',
  },
  {
    id: 'chat7',
    name: 'Michael Chen',
    role: 'IT Administrator',
    type: 'direct',
    isGroup: false,
    initials: 'MC',
    lastMessage: 'System maintenance scheduled for tonight',
    lastMessageSender: 'other', // Last message was received
    unread: 1,
    time: '07:45 AM',
    timestamp: '2025-11-14T07:45:00Z',
    avatar: '',
    messageCount: 4,
    status: 'sent',
    isOnline: true,
  },
  {
    id: 'chat8',
    name: 'Parent Committee',
    type: 'group',
    isGroup: true,
    initials: 'PC',
    members: 15,
    lastMessage: 'Fundraiser details attached',
    lastMessageSender: 'other', // Last message was received
    unread: 5,
    time: 'Yesterday',
    timestamp: '2025-11-13T10:00:00Z',
    avatar: '',
    messageCount: 12,
    status: 'sent',
  },
  {
    id: 'chat9',
    name: 'Emily Johnson',
    role: 'School Counselor',
    type: 'direct',
    isGroup: false,
    initials: 'EJ',
    lastMessage: 'Thanks for the update!',
    lastMessageSender: 'other', // Last message was received
    unread: 0,
    time: '3 days ago',
    timestamp: '2025-11-11T14:30:00Z',
    avatar: '', 
    messageCount: 6,
    status: 'read',
    isOnline: false,
  },
  {
    id: 'chat10',
    name: 'Sports Team Coaches',
    type: 'group',
    isGroup: true,
    initials: 'ST',
    members: 8,
    lastMessage: 'Practice schedule for next month',
    lastMessageSender: 'other', // Last message was received
    unread: 0,
    time: 'Last week',
    timestamp: '2025-11-07T09:00:00Z',
    avatar: '',
    messageCount: 15,
    status: 'read',
  },
];

/**
 * Message data stored separately by chatId
 * In production, messages would be fetched on-demand per chat via API
 * This prevents loading all messages for all chats at once
 * Only load messages when user opens a specific chat
 * 
 * Production approach:
 * - Fetch messages with pagination: GET /api/messages/:chatId?page=1&limit=50
 * - Implement infinite scroll or lazy loading
 * - Cache recently viewed chats
 */
export const messagesByChatId = {
  chat1: [
    { 
      id: 'msg1-1',
      chatId: 'chat1',
      sender: 'other', 
      initials: 'JT',
      text: 'Good morning!', 
      time: '08:45 AM',
      date: '2024-04-16T08:45:00',
      delivered: true,
      seen: true 
    },
    { 
      id: 'msg1-2',
      chatId: 'chat1',
      sender: 'me', 
      initials: 'YO',
      text: 'Morning! Hope you had a great weekend!', 
      time: '08:47 AM',
      date: '2024-04-16T08:47:00',
      delivered: true,
      seen: false 
    },
  ],
  chat2: [
    { 
      id: 'msg2-1',
      chatId: 'chat2',
      sender: 'other', 
      initials: 'DB',
      text: 'We are thinking warm browns...', 
      time: '09:22 AM',
      date: '2024-04-16T09:22:00',
      delivered: true,
      seen: true 
    },
    { 
      id: 'msg2-2',
      chatId: 'chat2',
      sender: 'me', 
      initials: 'YO',
      text: 'Love that idea!', 
      time: '09:38 AM',
      date: '2024-04-16T09:38:00',
      delivered: false,
      seen: false 
    },
  ],
  chat3: [],
  chat4: [
    {
      id: 'msg4-1',
      chatId: 'chat4',
      sender: 'other',
      initials: 'GD',
      text: 'Sure! It\'s a boutique coffee shop called "Java Haven." We want something modern yet cozy, with maybe a coffee cup incorporated into the design.',
      time: '09:22 AM',
      date: '2024-04-16T09:22:00',
      delivered: true,
      seen: true,
    },
    {
      id: 'msg4-2',
      chatId: 'chat4',
      sender: 'me',
      initials: 'YO',
      text: 'Got it! Do you have any color preferences or specific elements you\'d like to see in the logo?',
      time: '09:31 AM',
      date: '2024-04-16T09:31:00',
      delivered: true,
      seen: false,
    },
    {
      id: 'msg4-3',
      chatId: 'chat4',
      sender: 'other',
      initials: 'GD',
      text: 'We\'re thinking warm browns and cream colors. Maybe with a subtle steam effect rising from the cup?',
      time: '09:35 AM',
      date: '2024-04-16T09:35:00',
      delivered: true,
      seen: true,
    },
    {
      id: 'msg4-4',
      chatId: 'chat4',
      sender: 'me',
      initials: 'YO',
      text: 'I love that idea! The steam effect could add a really nice touch. Let me sketch out a few concepts and share them with you.',
      time: '09:38 AM',
      date: '2024-04-16T09:38:00',
      delivered: false,
      seen: false,
    },
    {
      id: 'msg4-5',
      chatId: 'chat4',
      sender: 'other',
      initials: 'GD',
      text: 'That would be amazing! When do you think you could have the initial concepts ready?',
      time: '09:40 AM',
      date: '2024-04-16T09:40:00',
      delivered: true,
      seen: true,
    },
    {
      id: 'msg4-6',
      chatId: 'chat4',
      sender: 'me',
      initials: 'YO',
      text: 'I can have 3-4 concepts ready by the end of this week. Does Friday work for you?',
      time: '09:42 AM',
      date: '2024-04-16T09:42:00',
      delivered: true,
      seen: true,
    },
    {
      id: 'msg4-7',
      chatId: 'chat4',
      sender: 'other',
      initials: 'GD',
      text: 'Friday is perfect! Really excited to see what you come up with.',
      time: '09:45 AM',
      date: '2024-04-16T09:45:00',
      delivered: true,
      seen: true,
    },
  ],
  chat5: [
    {
      id: 'msg5-1',
      chatId: 'chat5',
      sender: 'other',
      initials: 'SM',
      text: 'Hi! I wanted to discuss the upcoming math curriculum changes.',
      time: '08:15 AM',
      date: '2024-04-16T08:15:00',
      delivered: true,
      seen: true,
    },
    {
      id: 'msg5-2',
      chatId: 'chat5',
      sender: 'me',
      initials: 'YO',
      text: 'Sure! What changes are you thinking about?',
      time: '08:20 AM',
      date: '2024-04-16T08:20:00',
      delivered: true,
      seen: true,
    },
    {
      id: 'msg5-3',
      chatId: 'chat5',
      sender: 'other',
      initials: 'SM',
      text: 'We need to incorporate more practical examples in geometry lessons.',
      time: '08:22 AM',
      date: '2024-04-16T08:22:00',
      delivered: true,
      seen: false,
    },
    {
      id: 'msg5-4',
      chatId: 'chat5',
      sender: 'me',
      initials: 'YO',
      text: 'That sounds great! When can we meet to plan this?',
      time: '08:25 AM',
      date: '2024-04-16T08:25:00',
      delivered: true,
      seen: false,
    },
    {
      id: 'msg5-5',
      chatId: 'chat5',
      sender: 'other',
      initials: 'SM',
      text: 'Can we schedule a meeting for next week?',
      time: '08:30 AM',
      date: '2024-04-16T08:30:00',
      delivered: false,
      seen: false,
    },
  ],
  chat6: [
    {
      id: 'msg6-1',
      chatId: 'chat6',
      sender: 'other',
      initials: 'AL',
      text: 'Hey everyone! Science fair is coming up!',
      time: '10:00 AM',
      date: '2024-04-16T10:00:00',
      delivered: true,
      seen: true,
    },
    {
      id: 'msg6-2',
      chatId: 'chat6',
      sender: 'other',
      initials: 'PR',
      text: 'When is the deadline for project submissions?',
      time: '10:05 AM',
      date: '2024-04-16T10:05:00',
      delivered: true,
      seen: true,
    },
    {
      id: 'msg6-3',
      chatId: 'chat6',
      sender: 'me',
      initials: 'YO',
      text: 'The deadline is end of this month.',
      time: '10:10 AM',
      date: '2024-04-16T10:10:00',
      delivered: true,
      seen: true,
    },
    {
      id: 'msg6-4',
      chatId: 'chat6',
      sender: 'other',
      initials: 'AL',
      text: 'We should meet this Thursday to discuss project ideas.',
      time: '10:15 AM',
      date: '2024-04-16T10:15:00',
      delivered: true,
      seen: true,
    },
    {
      id: 'msg6-5',
      chatId: 'chat6',
      sender: 'other',
      initials: 'JK',
      text: 'Sounds good!',
      time: '10:20 AM',
      date: '2024-04-16T10:20:00',
      delivered: true,
      seen: true,
    },
    {
      id: 'msg6-6',
      chatId: 'chat6',
      sender: 'other',
      initials: 'PR',
      text: 'Can we meet at 3 PM?',
      time: '10:25 AM',
      date: '2024-04-16T10:25:00',
      delivered: true,
      seen: true,
    },
    {
      id: 'msg6-7',
      chatId: 'chat6',
      sender: 'me',
      initials: 'YO',
      text: 'Sorry, I have another meeting. How about 4 PM?',
      time: '10:30 AM',
      date: '2024-04-16T10:30:00',
      delivered: true,
      seen: false,
    },
    {
      id: 'msg6-8',
      chatId: 'chat6',
      sender: 'other',
      initials: 'AL',
      text: 'Meeting postponed to Thursday',
      time: '11:00 AM',
      date: '2024-04-16T11:00:00',
      delivered: true,
      seen: false,
    },
  ],
  chat7: [
    {
      id: 'msg7-1',
      chatId: 'chat7',
      sender: 'other',
      initials: 'MC',
      text: 'Hi, I need to inform you about scheduled maintenance.',
      time: '07:30 AM',
      date: '2024-04-16T07:30:00',
      delivered: true,
      seen: true,
    },
    {
      id: 'msg7-2',
      chatId: 'chat7',
      sender: 'me',
      initials: 'YO',
      text: 'When is it scheduled?',
      time: '07:35 AM',
      date: '2024-04-16T07:35:00',
      delivered: true,
      seen: true,
    },
    {
      id: 'msg7-3',
      chatId: 'chat7',
      sender: 'other',
      initials: 'MC',
      text: 'Tonight from 11 PM to 2 AM. All systems will be down.',
      time: '07:40 AM',
      date: '2024-04-16T07:40:00',
      delivered: true,
      seen: false,
    },
    {
      id: 'msg7-4',
      chatId: 'chat7',
      sender: 'other',
      initials: 'MC',
      text: 'System maintenance scheduled for tonight',
      time: '07:45 AM',
      date: '2024-04-16T07:45:00',
      delivered: false,
      seen: false,
    },
  ],
  chat8: [
    {
      id: 'msg8-1',
      chatId: 'chat8',
      sender: 'other',
      initials: 'DW',
      text: 'Good morning everyone! We have exciting news about the fundraiser.',
      time: '09:00 AM',
      date: '2024-04-16T09:00:00',
      delivered: true,
      seen: true,
    },
    {
      id: 'msg8-2',
      chatId: 'chat8',
      sender: 'other',
      initials: 'LB',
      text: 'What are the details?',
      time: '09:05 AM',
      date: '2024-04-16T09:05:00',
      delivered: true,
      seen: true,
    },
    {
      id: 'msg8-3',
      chatId: 'chat8',
      sender: 'other',
      initials: 'DW',
      text: 'We have reached 75% of our goal! Thank you all for your contributions.',
      time: '09:10 AM',
      date: '2024-04-16T09:10:00',
      delivered: true,
      seen: true,
    },
    {
      id: 'msg8-4',
      chatId: 'chat8',
      sender: 'me',
      initials: 'YO',
      text: 'That is amazing progress!',
      time: '09:15 AM',
      date: '2024-04-16T09:15:00',
      delivered: true,
      seen: true,
    },
    {
      id: 'msg8-5',
      chatId: 'chat8',
      sender: 'other',
      initials: 'RP',
      text: 'When is the deadline?',
      time: '09:20 AM',
      date: '2024-04-16T09:20:00',
      delivered: true,
      seen: true,
    },
    {
      id: 'msg8-6',
      chatId: 'chat8',
      sender: 'other',
      initials: 'DW',
      text: 'End of next month. We still have time!',
      time: '09:25 AM',
      date: '2024-04-16T09:25:00',
      delivered: true,
      seen: true,
    },
    {
      id: 'msg8-7',
      chatId: 'chat8',
      sender: 'other',
      initials: 'LB',
      text: 'I will share this with my network.',
      time: '09:30 AM',
      date: '2024-04-16T09:30:00',
      delivered: true,
      seen: true,
    },
    {
      id: 'msg8-8',
      chatId: 'chat8',
      sender: 'other',
      initials: 'DW',
      text: 'Thank you! I have attached the detailed plan.',
      time: '09:35 AM',
      date: '2024-04-16T09:35:00',
      delivered: true,
      seen: false,
    },
    {
      id: 'msg8-9',
      chatId: 'chat8',
      sender: 'other',
      initials: 'MG',
      text: 'Great work team!',
      time: '09:40 AM',
      date: '2024-04-16T09:40:00',
      delivered: true,
      seen: false,
    },
    {
      id: 'msg8-10',
      chatId: 'chat8',
      sender: 'me',
      initials: 'YO',
      text: 'Looking forward to seeing the details.',
      time: '09:42 AM',
      date: '2024-04-16T09:42:00',
      delivered: true,
      seen: false,
    },
    {
      id: 'msg8-11',
      chatId: 'chat8',
      sender: 'other',
      initials: 'RP',
      text: 'Can we schedule a committee meeting?',
      time: '09:45 AM',
      date: '2024-04-16T09:45:00',
      delivered: false,
      seen: false,
    },
    {
      id: 'msg8-12',
      chatId: 'chat8',
      sender: 'other',
      initials: 'DW',
      text: 'Fundraiser details attached',
      time: '09:50 AM',
      date: '2024-04-16T09:50:00',
      delivered: false,
      seen: false,
    },
  ],
  chat9: [
    {
      id: 'msg9-1',
      chatId: 'chat9',
      sender: 'other',
      initials: 'EJ',
      text: 'Hi! I wanted to check in about student counseling sessions.',
      time: '02:00 PM',
      date: '2024-04-16T14:00:00',
      delivered: true,
      seen: true,
    },
    {
      id: 'msg9-2',
      chatId: 'chat9',
      sender: 'me',
      initials: 'YO',
      text: 'Yes, everything is going well. The students are responding positively.',
      time: '02:15 PM',
      date: '2024-04-16T14:15:00',
      delivered: true,
      seen: true,
    },
    {
      id: 'msg9-3',
      chatId: 'chat9',
      sender: 'other',
      initials: 'EJ',
      text: 'That is wonderful to hear!',
      time: '02:20 PM',
      date: '2024-04-16T14:20:00',
      delivered: true,
      seen: true,
    },
    {
      id: 'msg9-4',
      chatId: 'chat9',
      sender: 'me',
      initials: 'YO',
      text: 'I will send you the progress report by end of day.',
      time: '02:25 PM',
      date: '2024-04-16T14:25:00',
      delivered: true,
      seen: true,
    },
    {
      id: 'msg9-5',
      chatId: 'chat9',
      sender: 'other',
      initials: 'EJ',
      text: 'Perfect! Looking forward to it.',
      time: '02:30 PM',
      date: '2024-04-16T14:30:00',
      delivered: true,
      seen: true,
    },
    {
      id: 'msg9-6',
      chatId: 'chat9',
      sender: 'other',
      initials: 'EJ',
      text: 'Thanks for the update!',
      time: '02:35 PM',
      date: '2024-04-16T14:35:00',
      delivered: true,
      seen: false,
    },
  ],
  chat10: [
    {
      id: 'msg10-1',
      chatId: 'chat10',
      sender: 'other',
      initials: 'TC',
      text: 'Hello coaches! Time to plan next month practice schedule.',
      time: '03:00 PM',
      date: '2024-04-16T15:00:00',
      delivered: true,
      seen: true,
    },
    {
      id: 'msg10-2',
      chatId: 'chat10',
      sender: 'other',
      initials: 'KB',
      text: 'What days are available for basketball practice?',
      time: '03:05 PM',
      date: '2024-04-16T15:05:00',
      delivered: true,
      seen: true,
    },
    {
      id: 'msg10-3',
      chatId: 'chat10',
      sender: 'me',
      initials: 'YO',
      text: 'Monday, Wednesday, and Friday afternoons.',
      time: '03:10 PM',
      date: '2024-04-16T15:10:00',
      delivered: true,
      seen: true,
    },
    {
      id: 'msg10-4',
      chatId: 'chat10',
      sender: 'other',
      initials: 'JS',
      text: 'We need the gym on Tuesdays for volleyball.',
      time: '03:15 PM',
      date: '2024-04-16T15:15:00',
      delivered: true,
      seen: true,
    },
    {
      id: 'msg10-5',
      chatId: 'chat10',
      sender: 'other',
      initials: 'TC',
      text: 'Let me create a shared calendar for everyone.',
      time: '03:20 PM',
      date: '2024-04-16T15:20:00',
      delivered: true,
      seen: true,
    },
    {
      id: 'msg10-6',
      chatId: 'chat10',
      sender: 'other',
      initials: 'KB',
      text: 'That would be very helpful!',
      time: '03:25 PM',
      date: '2024-04-16T15:25:00',
      delivered: true,
      seen: true,
    },
    {
      id: 'msg10-7',
      chatId: 'chat10',
      sender: 'me',
      initials: 'YO',
      text: 'Also, we need to discuss equipment upgrades.',
      time: '03:30 PM',
      date: '2024-04-16T15:30:00',
      delivered: true,
      seen: true,
    },
    {
      id: 'msg10-8',
      chatId: 'chat10',
      sender: 'other',
      initials: 'JS',
      text: 'Yes, the volleyball nets need replacement.',
      time: '03:35 PM',
      date: '2024-04-16T15:35:00',
      delivered: true,
      seen: true,
    },
    {
      id: 'msg10-9',
      chatId: 'chat10',
      sender: 'other',
      initials: 'TC',
      text: 'I will submit a request to the administration.',
      time: '03:40 PM',
      date: '2024-04-16T15:40:00',
      delivered: true,
      seen: true,
    },
    {
      id: 'msg10-10',
      chatId: 'chat10',
      sender: 'other',
      initials: 'KB',
      text: 'When can we expect the new equipment?',
      time: '03:45 PM',
      date: '2024-04-16T15:45:00',
      delivered: true,
      seen: true,
    },
    {
      id: 'msg10-11',
      chatId: 'chat10',
      sender: 'other',
      initials: 'TC',
      text: 'Should arrive within 2-3 weeks if approved.',
      time: '03:50 PM',
      date: '2024-04-16T15:50:00',
      delivered: true,
      seen: false,
    },
    {
      id: 'msg10-12',
      chatId: 'chat10',
      sender: 'me',
      initials: 'YO',
      text: 'Sounds good. Thanks for coordinating!',
      time: '03:55 PM',
      date: '2024-04-16T15:55:00',
      delivered: true,
      seen: false,
    },
    {
      id: 'msg10-13',
      chatId: 'chat10',
      sender: 'other',
      initials: 'JS',
      text: 'Appreciate it!',
      time: '04:00 PM',
      date: '2024-04-16T16:00:00',
      delivered: true,
      seen: false,
    },
    {
      id: 'msg10-14',
      chatId: 'chat10',
      sender: 'other',
      initials: 'KB',
      text: 'Looking forward to the new schedule.',
      time: '04:05 PM',
      date: '2024-04-16T16:05:00',
      delivered: false,
      seen: false,
    },
    {
      id: 'msg10-15',
      chatId: 'chat10',
      sender: 'other',
      initials: 'TC',
      text: 'Practice schedule for next month',
      time: '04:10 PM',
      date: '2024-04-16T16:10:00',
      delivered: false,
      seen: false,
    },
  ],
};

/**
 * Helper function to get messages for a specific chat
 * In production, this would be an API call like:
 * const messages = await fetchMessages(chatId, { page, limit });
 * 
 * @param {string} chatId - The chat ID to fetch messages for
 * @returns {Array} messages - Array of message objects
 */
export const getMessagesByChatId = (chatId) => {
  return messagesByChatId[chatId] || [];
};

/**
 * Helper function to get chat metadata by ID
 * @param {string} chatId 
 * @returns {Object|null} chat metadata
 */
export const getChatById = (chatId) => {
  return chatData.find(chat => chat.id === chatId) || null;
};
