// ─── Alumni Mock Data ──────────────────────────────────────────────────────────
// Prefix: alm-*  |  All ids: ALM-XXXX

export const BATCH_YEARS = ["2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023"];

export const INDUSTRIES = [
  { value: "technology",   label: "Technology" },
  { value: "finance",      label: "Finance & Banking" },
  { value: "healthcare",   label: "Healthcare" },
  { value: "education",    label: "Education" },
  { value: "engineering",  label: "Engineering" },
  { value: "arts",         label: "Arts & Media" },
  { value: "government",   label: "Government / IAS" },
  { value: "sports",       label: "Sports" },
  { value: "business",     label: "Business / Startup" },
];

export const MENTOR_CATEGORIES = [
  { value: "career",          label: "Career Guidance",   icon: "🎯" },
  { value: "higher-studies",  label: "Higher Studies",    icon: "🎓" },
  { value: "entrepreneurship",label: "Entrepreneurship",  icon: "🚀" },
  { value: "technology",      label: "Technology",        icon: "💻" },
  { value: "business",        label: "Business",          icon: "💼" },
  { value: "arts-sports",     label: "Arts & Sports",     icon: "🎨" },
];

export const VERIFICATION_STATUSES = [
  { value: "verified",  label: "Verified",  color: "#16a34a", bg: "rgba(22,163,74,.1)"  },
  { value: "pending",   label: "Pending",   color: "#d97706", bg: "rgba(217,119,6,.1)"  },
  { value: "rejected",  label: "Rejected",  color: "#dc2626", bg: "rgba(220,38,38,.1)"  },
];

export const MOCK_ALUMNI = [
  {
    id: "ALM-001",
    name: "Rahul Menon",
    admissionNo: "ADM-2018-001",
    initials: "RM",
    avatarColor: "#2563eb",
    avatarImg: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&h=200&q=85",
    batch: "2018",
    graduation: "2022",
    designation: "Senior Software Engineer",
    company: "Google India",
    industry: "technology",
    location: "Bangalore",
    country: "India",
    isAbroad: false,
    verificationStatus: "verified",
    isMentor: true,
    mentorCategory: "technology",
    mentorStatus: "active",
    experience: "4 years",
    bio: "Full-stack developer passionate about distributed systems, open-source software, and mentoring the next generation of engineers. Led multiple large-scale platform migrations at Google.",
    higherEd: { degree: "B.Tech Computer Science", institution: "NIT Calicut", year: "2022" },
    achievements: ["Google Summer of Code 2021", "Dean's List 2020–2022", "Best Final Year Project"],
    tags: ["#golang", "#distributed-systems", "#mentoring"],
    socialLinks: { linkedin: "#", github: "#", twitter: "#" },
    joinedAt: "2022-05-10",
    featured: true,
  },
  {
    id: "ALM-002",
    name: "Priya Krishnan",
    admissionNo: "ADM-2017-045",
    initials: "PK",
    avatarColor: "#7c3aed",
    avatarImg: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&h=200&q=85",
    batch: "2017",
    graduation: "2021",
    designation: "IAS Officer",
    company: "Government of Kerala",
    industry: "government",
    location: "Thiruvananthapuram",
    country: "India",
    isAbroad: false,
    verificationStatus: "verified",
    isMentor: true,
    mentorCategory: "career",
    mentorStatus: "active",
    experience: "3 years",
    bio: "IAS officer (2022 batch) committed to public service and rural development. UPSC rank holder and passionate about governance innovation.",
    higherEd: { degree: "BA History (Hons)", institution: "Lady Shri Ram College, Delhi", year: "2021" },
    achievements: ["UPSC CSE Rank 47 (2022)", "State Topper – Class XII", "National Essay Competition Winner"],
    tags: ["#governance", "#policy", "#UPSC"],
    socialLinks: { linkedin: "#", twitter: "#" },
    joinedAt: "2023-01-15",
    featured: true,
  },
  {
    id: "ALM-003",
    name: "Arun Sharma",
    admissionNo: "ADM-2019-012",
    initials: "AS",
    avatarColor: "#059669",
    avatarImg: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&h=200&q=85",
    batch: "2019",
    graduation: "2023",
    designation: "Co-founder & CTO",
    company: "EduTech Startup (Stealth)",
    industry: "business",
    location: "Hyderabad",
    country: "India",
    isAbroad: false,
    verificationStatus: "verified",
    isMentor: true,
    mentorCategory: "entrepreneurship",
    mentorStatus: "active",
    experience: "2 years",
    bio: "First-generation entrepreneur building AI-powered ed-tech solutions. Bootstrapped two ventures and raised seed funding from prominent angel investors.",
    higherEd: { degree: "MBA", institution: "IIM Ahmedabad", year: "2023" },
    achievements: ["Forbes 30 Under 30 India 2025", "YC S23 Alumni", "Best Entrepreneur Award – School 2019"],
    tags: ["#startup", "#AI", "#edtech"],
    socialLinks: { linkedin: "#", twitter: "#", github: "#" },
    joinedAt: "2023-07-20",
    featured: true,
  },
  {
    id: "ALM-004",
    name: "Divya Nair",
    admissionNo: "ADM-2016-088",
    initials: "DN",
    avatarColor: "#db2777",
    avatarImg: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=200&h=200&q=85",
    batch: "2016",
    graduation: "2020",
    designation: "Cardiologist",
    company: "AIIMS Delhi",
    industry: "healthcare",
    location: "New Delhi",
    country: "India",
    isAbroad: false,
    verificationStatus: "verified",
    isMentor: false,
    mentorCategory: "career",
    mentorStatus: "inactive",
    experience: "5 years",
    bio: "Practising cardiologist at AIIMS Delhi specialising in interventional cardiology. Published research on preventive cardiac care in rural populations.",
    higherEd: { degree: "MBBS + MD Cardiology", institution: "AIIMS Delhi", year: "2026" },
    achievements: ["ICMR Research Grant 2024", "Best Medical Graduate – School 2020", "Gold Medal – MBBS"],
    tags: ["#medicine", "#cardiology", "#research"],
    socialLinks: { linkedin: "#" },
    joinedAt: "2021-03-12",
    featured: false,
  },
  {
    id: "ALM-005",
    name: "Siddharth Nambiar",
    admissionNo: "ADM-2015-007",
    initials: "SN",
    avatarColor: "#ea580c",
    avatarImg: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&h=200&q=85",
    batch: "2015",
    graduation: "2019",
    designation: "Machine Learning Engineer",
    company: "Meta (London)",
    industry: "technology",
    location: "London",
    country: "UK",
    isAbroad: true,
    verificationStatus: "verified",
    isMentor: true,
    mentorCategory: "higher-studies",
    mentorStatus: "active",
    experience: "7 years",
    bio: "ML engineer at Meta London working on recommendation systems. MS from Stanford. Guides students on international university applications and STEM careers abroad.",
    higherEd: { degree: "MS Computer Science", institution: "Stanford University", year: "2021" },
    achievements: ["Stanford Fellowship 2019", "Best Project – AI Track 2019", "NeurIPS Paper 2023"],
    tags: ["#ML", "#stanford", "#abroad"],
    socialLinks: { linkedin: "#", github: "#", twitter: "#" },
    joinedAt: "2020-08-04",
    featured: false,
  },
  {
    id: "ALM-006",
    name: "Kavya Rajendran",
    admissionNo: "ADM-2020-031",
    initials: "KR",
    avatarColor: "#0891b2",
    avatarImg: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=200&h=200&q=85",
    batch: "2020",
    graduation: "2024",
    designation: "UX Designer",
    company: "Flipkart",
    industry: "technology",
    location: "Bangalore",
    country: "India",
    isAbroad: false,
    verificationStatus: "verified",
    isMentor: false,
    mentorCategory: null,
    mentorStatus: "inactive",
    experience: "2 years",
    bio: "Product designer shaping customer-centric e-commerce experiences at Flipkart. Passionate about design systems, accessibility, and motion design.",
    higherEd: { degree: "B.Des Interaction Design", institution: "NID Ahmedabad", year: "2024" },
    achievements: ["Flipkart Design Excellence Award 2025", "National Design Award 2024"],
    tags: ["#design", "#UX", "#figma"],
    socialLinks: { linkedin: "#", twitter: "#" },
    joinedAt: "2024-06-01",
    featured: false,
  },
  {
    id: "ALM-007",
    name: "Mohammed Ashraf",
    admissionNo: "ADM-2018-056",
    initials: "MA",
    avatarColor: "#0d9488",
    avatarImg: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=200&h=200&q=85",
    batch: "2018",
    graduation: "2022",
    designation: "Investment Analyst",
    company: "Goldman Sachs Singapore",
    industry: "finance",
    location: "Singapore",
    country: "Singapore",
    isAbroad: true,
    verificationStatus: "verified",
    isMentor: true,
    mentorCategory: "career",
    mentorStatus: "active",
    experience: "4 years",
    bio: "Investment analyst covering South-East Asian emerging markets. CFA Level III candidate. Mentors students interested in finance careers and CFA prep.",
    higherEd: { degree: "B.Com Finance (Hons)", institution: "Christ University Bangalore", year: "2022" },
    achievements: ["Goldman Sachs Analyst Excellence 2024", "CFA Institute Scholar 2023"],
    tags: ["#finance", "#CFA", "#Singapore"],
    socialLinks: { linkedin: "#" },
    joinedAt: "2022-09-18",
    featured: false,
  },
  {
    id: "ALM-008",
    name: "Ananya Pillai",
    admissionNo: "ADM-2021-003",
    initials: "AP",
    avatarColor: "#9333ea",
    avatarImg: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&h=200&q=85",
    batch: "2021",
    graduation: "2025",
    designation: "Civil Engineer",
    company: "L&T Construction",
    industry: "engineering",
    location: "Mumbai",
    country: "India",
    isAbroad: false,
    verificationStatus: "pending",
    isMentor: false,
    mentorCategory: null,
    mentorStatus: "inactive",
    experience: "1 year",
    bio: "Civil engineer at L&T specialising in bridge infrastructure. Passionate about sustainable construction and smart city planning.",
    higherEd: { degree: "B.Tech Civil Engineering", institution: "VJTI Mumbai", year: "2025" },
    achievements: ["Best Graduate – Engineering Dept 2025"],
    tags: ["#civil", "#infrastructure"],
    socialLinks: { linkedin: "#" },
    joinedAt: "2025-08-10",
    featured: false,
  },
  {
    id: "ALM-009",
    name: "Rohan George",
    admissionNo: "ADM-2017-092",
    initials: "RG",
    avatarColor: "#dc2626",
    avatarImg: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&h=200&q=85",
    batch: "2017",
    graduation: "2021",
    designation: "National-level Cricketer",
    company: "Kerala Cricket Team",
    industry: "sports",
    location: "Kochi",
    country: "India",
    isAbroad: false,
    verificationStatus: "verified",
    isMentor: true,
    mentorCategory: "arts-sports",
    mentorStatus: "active",
    experience: "5 years",
    bio: "State-level cricketer representing Kerala in the Ranji Trophy. Passionate about youth sports development and school-level cricket coaching.",
    higherEd: { degree: "BPEd", institution: "LNCPE Thiruvananthapuram", year: "2021" },
    achievements: ["Ranji Trophy Debut 2022", "Best Cricketer – School 2017", "U-19 National Camp 2016"],
    tags: ["#cricket", "#sports", "#coaching"],
    socialLinks: { linkedin: "#", twitter: "#" },
    joinedAt: "2022-02-14",
    featured: false,
  },
  {
    id: "ALM-010",
    name: "Sneha Thomas",
    admissionNo: "ADM-2019-077",
    initials: "ST",
    avatarColor: "#7c2d12",
    avatarImg: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&h=200&q=85",
    batch: "2019",
    graduation: "2023",
    designation: "Content Creator & Artist",
    company: "Independent",
    industry: "arts",
    location: "Kochi",
    country: "India",
    isAbroad: false,
    verificationStatus: "verified",
    isMentor: false,
    mentorCategory: null,
    mentorStatus: "inactive",
    experience: "3 years",
    bio: "Visual artist and digital content creator with 500K+ followers. Focuses on cultural storytelling, traditional art forms, and design for social impact.",
    higherEd: { degree: "BFA Fine Arts", institution: "College of Fine Arts Thrissur", year: "2023" },
    achievements: ["Kerala State Young Artist Award 2024", "500K YouTube Milestone", "TEDx Speaker 2025"],
    tags: ["#art", "#content", "#culture"],
    socialLinks: { linkedin: "#", twitter: "#" },
    joinedAt: "2023-11-05",
    featured: false,
  },
  {
    id: "ALM-011",
    name: "Vikram Subramaniam",
    admissionNo: "ADM-2016-014",
    initials: "VS",
    avatarColor: "#1d4ed8",
    avatarImg: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=200&h=200&q=85",
    batch: "2016",
    graduation: "2020",
    designation: "Data Scientist",
    company: "Microsoft Research",
    industry: "technology",
    location: "Redmond, WA",
    country: "USA",
    isAbroad: true,
    verificationStatus: "verified",
    isMentor: true,
    mentorCategory: "technology",
    mentorStatus: "active",
    experience: "6 years",
    bio: "Data scientist at Microsoft Research working on NLP and responsible AI. PhD from CMU. Mentors students eyeing top US MS/PhD programs.",
    higherEd: { degree: "PhD Computer Science", institution: "Carnegie Mellon University", year: "2025" },
    achievements: ["Microsoft Research Fellowship 2022", "ACL Paper 2024", "CMU PhD Scholarship"],
    tags: ["#NLP", "#PhD", "#researchAI"],
    socialLinks: { linkedin: "#", github: "#" },
    joinedAt: "2021-05-22",
    featured: true,
  },
  {
    id: "ALM-012",
    name: "Meera Chandran",
    admissionNo: "ADM-2022-008",
    initials: "MC",
    avatarColor: "#be185d",
    avatarImg: "https://images.unsplash.com/photo-1548142813-c348350df52b?auto=format&fit=crop&w=200&h=200&q=85",
    batch: "2022",
    graduation: "2026",
    designation: "Junior Finance Analyst",
    company: "ICICI Bank",
    industry: "finance",
    location: "Chennai",
    country: "India",
    isAbroad: false,
    verificationStatus: "pending",
    isMentor: false,
    mentorCategory: null,
    mentorStatus: "inactive",
    experience: "< 1 year",
    bio: "Recent graduate started career in corporate banking. Enthusiastic about fintech and financial literacy initiatives.",
    higherEd: { degree: "B.Com Finance", institution: "Loyola College Chennai", year: "2026" },
    achievements: ["University Gold Medal – B.Com 2026"],
    tags: ["#finance", "#banking"],
    socialLinks: { linkedin: "#" },
    joinedAt: "2026-03-01",
    featured: false,
  },
  {
    id: "ALM-013",
    name: "Ajay Varma",
    admissionNo: "ADM-2015-033",
    initials: "AV",
    avatarColor: "#b45309",
    avatarImg: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=200&h=200&q=85",
    batch: "2015",
    graduation: "2019",
    designation: "Chartered Accountant",
    company: "Deloitte India",
    industry: "finance",
    location: "Mumbai",
    country: "India",
    isAbroad: false,
    verificationStatus: "rejected",
    isMentor: false,
    mentorCategory: null,
    mentorStatus: "inactive",
    experience: "7 years",
    bio: "Senior CA at Deloitte specialising in audit and M&A advisory. Fellowship at ICAI.",
    higherEd: { degree: "CA + BCom", institution: "ICAI", year: "2021" },
    achievements: ["ICAI All India Rank 12", "Best Student Award 2015"],
    tags: ["#CA", "#audit", "#M&A"],
    socialLinks: { linkedin: "#" },
    joinedAt: "2019-07-01",
    featured: false,
  },
  {
    id: "ALM-014",
    name: "Lakshmi Iyer",
    admissionNo: "ADM-2020-054",
    initials: "LI",
    avatarColor: "#6d28d9",
    avatarImg: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=200&h=200&q=85",
    batch: "2020",
    graduation: "2024",
    designation: "Research Associate",
    company: "ISRO",
    industry: "engineering",
    location: "Sriharikota",
    country: "India",
    isAbroad: false,
    verificationStatus: "verified",
    isMentor: false,
    mentorCategory: null,
    mentorStatus: "inactive",
    experience: "2 years",
    bio: "Aerospace engineer at ISRO working on satellite communication systems. Passionate about inspiring young girls into STEM careers.",
    higherEd: { degree: "B.Tech Aerospace Engineering", institution: "IIT Madras", year: "2024" },
    achievements: ["ISRO Excellence Award 2025", "IIT Madras Gold Medal", "Best Science Student – School 2020"],
    tags: ["#ISRO", "#aerospace", "#STEM"],
    socialLinks: { linkedin: "#", twitter: "#" },
    joinedAt: "2024-09-20",
    featured: false,
  },
  {
    id: "ALM-015",
    name: "Jayesh Kumar",
    admissionNo: "ADM-2023-002",
    initials: "JK",
    avatarColor: "#0f766e",
    avatarImg: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=200&h=200&q=85",
    batch: "2023",
    graduation: "2027",
    designation: "B.Tech Student",
    company: "NIT Trichy",
    industry: "education",
    location: "Trichy",
    country: "India",
    isAbroad: false,
    verificationStatus: "pending",
    isMentor: false,
    mentorCategory: null,
    mentorStatus: "inactive",
    experience: "0 years",
    bio: "Undergraduate student at NIT Trichy. Active in robotics club and competitive programming. Recent school pass-out seeking alumni network connections.",
    higherEd: { degree: "B.Tech (in progress)", institution: "NIT Trichy", year: "—" },
    achievements: ["ICPC Regional Finalist 2026", "Best Outgoing Student – School 2023"],
    tags: ["#robotics", "#compProg"],
    socialLinks: { linkedin: "#", github: "#" },
    joinedAt: "2027-01-10",
    featured: false,
  },
];

// ─── Mentorship Requests ──────────────────────────────────────────────────────
export const MOCK_MENTORSHIP_REQUESTS = [
  {
    id: "MR-001",
    alumniId: "ALM-001",
    alumniName: "Rahul Menon",
    initials: "RM",
    avatarColor: "#2563eb",
    category: "technology",
    profession: "Software Engineer",
    company: "Google India",
    experience: "4 years",
    availability: "Weekends",
    status: "pending",
    submittedAt: "2026-05-10",
    note: "Happy to mentor students interested in backend, system design, and interview prep.",
  },
  {
    id: "MR-002",
    alumniId: "ALM-003",
    alumniName: "Arun Sharma",
    initials: "AS",
    avatarColor: "#059669",
    category: "entrepreneurship",
    profession: "Co-founder & CTO",
    company: "EduTech Startup",
    experience: "2 years",
    availability: "Bi-weekly",
    status: "approved",
    submittedAt: "2026-03-01",
    note: "Can guide aspiring entrepreneurs through ideation, fundraising, and product-market fit.",
  },
  {
    id: "MR-003",
    alumniId: "ALM-005",
    alumniName: "Siddharth Nambiar",
    initials: "SN",
    avatarColor: "#ea580c",
    category: "higher-studies",
    profession: "ML Engineer",
    company: "Meta London",
    experience: "7 years",
    availability: "Monthly",
    status: "approved",
    submittedAt: "2026-01-20",
    note: "Guidance on GRE, SOP writing, and choosing the right grad programs in CS/AI.",
  },
  {
    id: "MR-004",
    alumniId: "ALM-007",
    alumniName: "Mohammed Ashraf",
    initials: "MA",
    avatarColor: "#0d9488",
    category: "career",
    profession: "Investment Analyst",
    company: "Goldman Sachs",
    experience: "4 years",
    availability: "Weekends",
    status: "pending",
    submittedAt: "2026-05-15",
    note: "CFA prep guidance, finance career paths, and networking in investment banking.",
  },
  {
    id: "MR-005",
    alumniId: "ALM-009",
    alumniName: "Rohan George",
    initials: "RG",
    avatarColor: "#dc2626",
    category: "arts-sports",
    profession: "Cricketer",
    company: "Kerala Cricket Team",
    experience: "5 years",
    availability: "Weekly",
    status: "approved",
    submittedAt: "2026-02-28",
    note: "Support for students pursuing professional sports careers and scholarships.",
  },
  {
    id: "MR-006",
    alumniId: "ALM-011",
    alumniName: "Vikram Subramaniam",
    initials: "VS",
    avatarColor: "#1d4ed8",
    category: "technology",
    profession: "Data Scientist",
    company: "Microsoft Research",
    experience: "6 years",
    availability: "Bi-weekly",
    status: "pending",
    submittedAt: "2026-05-18",
    note: "PhD application strategy, research SOP, and NLP/AI project guidance.",
  },
  {
    id: "MR-007",
    alumniId: "ALM-002",
    alumniName: "Priya Krishnan",
    initials: "PK",
    avatarColor: "#7c3aed",
    category: "career",
    profession: "IAS Officer",
    company: "Govt. of Kerala",
    experience: "3 years",
    availability: "Monthly",
    status: "approved",
    submittedAt: "2026-01-05",
    note: "UPSC strategy, optional subject selection, and civil services preparation guidance.",
  },
  {
    id: "MR-008",
    alumniId: "ALM-013",
    alumniName: "Ajay Varma",
    initials: "AV",
    avatarColor: "#b45309",
    category: "career",
    profession: "Chartered Accountant",
    company: "Deloitte India",
    experience: "7 years",
    availability: "Weekends",
    status: "rejected",
    submittedAt: "2026-04-20",
    note: "CA prep and finance career mentoring.",
  },
];

// ─── Alumni Events ────────────────────────────────────────────────────────────
export const MOCK_EVENTS = [
  {
    id: "EVT-001",
    title: "Annual Alumni Reunion 2026",
    type: "reunion",
    date: "2026-07-15",
    venue: "School Auditorium, Main Campus",
    description: "Annual gathering for all batch alumni. Networking, cultural programs, and campus tour.",
    participationCount: 142,
    registrationStatus: "open",
    status: "upcoming",
  },
  {
    id: "EVT-002",
    title: "Tech Talk: AI & Future of Work",
    type: "webinar",
    date: "2026-06-05",
    venue: "Online (Zoom)",
    description: "Alumni panel discussion on AI trends and career opportunities with alumni from top tech companies.",
    participationCount: 87,
    registrationStatus: "open",
    status: "upcoming",
  },
  {
    id: "EVT-003",
    title: "Career Guidance Seminar – Batch 2023",
    type: "networking",
    date: "2026-05-30",
    venue: "School Seminar Hall",
    description: "Senior alumni share career insights with recent pass-out batch. Mock interviews included.",
    participationCount: 63,
    registrationStatus: "closed",
    status: "upcoming",
  },
  {
    id: "EVT-004",
    title: "Alumni Sports Day 2026",
    type: "reunion",
    date: "2026-08-10",
    venue: "School Sports Ground",
    description: "Inter-batch sports competition and cultural fest for alumni and current students.",
    participationCount: 210,
    registrationStatus: "open",
    status: "upcoming",
  },
  {
    id: "EVT-005",
    title: "Entrepreneurs Networking Dinner",
    type: "networking",
    date: "2025-12-18",
    venue: "The Leela Palace, Kochi",
    description: "Exclusive alumni startup networking dinner. 40+ alumnus entrepreneurs and investors.",
    participationCount: 41,
    registrationStatus: "closed",
    status: "past",
  },
  {
    id: "EVT-006",
    title: "STEM Career Panel – Batch 2022",
    type: "webinar",
    date: "2025-11-10",
    venue: "Online (Google Meet)",
    description: "Alumni panel on STEM higher education pathways, internships, and research opportunities.",
    participationCount: 124,
    registrationStatus: "closed",
    status: "past",
  },
];

// ─── Achievements ─────────────────────────────────────────────────────────────
export const MOCK_ACHIEVEMENTS = [
  {
    id: "ACH-001",
    alumniId: "ALM-002",
    alumniName: "Priya Krishnan",
    initials: "PK",
    avatarColor: "#7c3aed",
    batch: "2017",
    title: "UPSC CSE Rank 47",
    category: "government",
    description: "Cleared UPSC Civil Services Exam securing All India Rank 47 in 2022, becoming one of the youngest IAS officers from the school.",
    year: "2022",
    featured: true,
  },
  {
    id: "ACH-002",
    alumniId: "ALM-003",
    alumniName: "Arun Sharma",
    initials: "AS",
    avatarColor: "#059669",
    batch: "2019",
    title: "Forbes 30 Under 30 – India",
    category: "business",
    description: "Named in Forbes India's prestigious 30 Under 30 list (2025) for building an AI-powered ed-tech startup that reached 100,000 students.",
    year: "2025",
    featured: true,
  },
  {
    id: "ACH-003",
    alumniId: "ALM-001",
    alumniName: "Rahul Menon",
    initials: "RM",
    avatarColor: "#2563eb",
    batch: "2018",
    title: "Google Summer of Code Mentor",
    category: "technology",
    description: "Selected as a GSoC organisation mentor for an open-source project with 15,000 GitHub stars, guiding 8 student contributors globally.",
    year: "2024",
    featured: false,
  },
  {
    id: "ACH-004",
    alumniId: "ALM-009",
    alumniName: "Rohan George",
    initials: "RG",
    avatarColor: "#dc2626",
    batch: "2017",
    title: "Ranji Trophy Debut",
    category: "sports",
    description: "Debuted for Kerala Cricket Team in the Ranji Trophy 2022, scoring a century on debut. Fastest alumnus to represent state cricket.",
    year: "2022",
    featured: true,
  },
  {
    id: "ACH-005",
    alumniId: "ALM-011",
    alumniName: "Vikram Subramaniam",
    initials: "VS",
    avatarColor: "#1d4ed8",
    batch: "2016",
    title: "ACL 2024 Paper Accepted",
    category: "technology",
    description: "Research paper on multilingual transformer models accepted at ACL 2024, one of the top NLP conferences globally.",
    year: "2024",
    featured: false,
  },
  {
    id: "ACH-006",
    alumniId: "ALM-014",
    alumniName: "Lakshmi Iyer",
    initials: "LI",
    avatarColor: "#6d28d9",
    batch: "2020",
    title: "ISRO Excellence Award",
    category: "engineering",
    description: "Awarded ISRO's annual excellence recognition for contributions to satellite communication system design under the GSAT mission.",
    year: "2025",
    featured: false,
  },
];

// ─── Testimonials ─────────────────────────────────────────────────────────────
export const MOCK_TESTIMONIALS = [
  {
    id: "TST-001",
    alumniId: "ALM-001",
    alumniName: "Rahul Menon",
    initials: "RM",
    avatarColor: "#2563eb",
    batch: "2018",
    designation: "Sr. Software Engineer, Google",
    quote: "The school gave me the discipline and curiosity to succeed in a competitive world. Every teacher who believed in me is part of my story at Google.",
    featured: true,
  },
  {
    id: "TST-002",
    alumniId: "ALM-002",
    alumniName: "Priya Krishnan",
    initials: "PK",
    avatarColor: "#7c3aed",
    batch: "2017",
    designation: "IAS Officer, Kerala Cadre",
    quote: "The values of integrity and service drilled into us in school prepared me more than any coaching class ever could for public service.",
    featured: true,
  },
  {
    id: "TST-003",
    alumniId: "ALM-003",
    alumniName: "Arun Sharma",
    initials: "AS",
    avatarColor: "#059669",
    batch: "2019",
    designation: "Co-founder, EduTech Startup",
    quote: "My entrepreneurship journey began with a science fair project here. The school taught me that failure is just a detour, not a dead end.",
    featured: false,
  },
  {
    id: "TST-004",
    alumniId: "ALM-009",
    alumniName: "Rohan George",
    initials: "RG",
    avatarColor: "#dc2626",
    batch: "2017",
    designation: "Cricketer, Kerala Team",
    quote: "Sports and academics hand-in-hand here taught me teamwork like nothing else. The cricket pitch was my classroom too.",
    featured: false,
  },
  {
    id: "TST-005",
    alumniId: "ALM-005",
    alumniName: "Siddharth Nambiar",
    initials: "SN",
    avatarColor: "#ea580c",
    batch: "2015",
    designation: "ML Engineer, Meta London",
    quote: "Getting into Stanford felt impossible until I had alumni like this school's network pushing me to apply. That support changed my life.",
    featured: true,
  },
  {
    id: "TST-006",
    alumniId: "ALM-014",
    alumniName: "Lakshmi Iyer",
    initials: "LI",
    avatarColor: "#6d28d9",
    batch: "2020",
    designation: "Research Associate, ISRO",
    quote: "Working on a rocket that orbits Earth — I still can't believe it. My passion for science was ignited right here in this school's physics lab.",
    featured: false,
  },
];

// ─── Contributions ────────────────────────────────────────────────────────────
export const MOCK_CONTRIBUTIONS = [
  { id: "CON-001", alumniName: "Arun Sharma", initials: "AS", avatarColor: "#059669", batch: "2019", type: "Scholarship Fund", amount: "₹1,00,000", date: "2025-12-20", note: "Annual merit scholarship for economically weaker section students." },
  { id: "CON-002", alumniName: "Rahul Menon",  initials: "RM", avatarColor: "#2563eb", batch: "2018", type: "Lab Equipment",  amount: "₹45,000",  date: "2026-01-14", note: "Donated computer peripherals for the school coding lab." },
  { id: "CON-003", alumniName: "Priya Krishnan", initials: "PK", avatarColor: "#7c3aed", batch: "2017", type: "Book Donation",  amount: "200 books", date: "2026-03-05", note: "UPSC preparation library books for the school library." },
  { id: "CON-004", alumniName: "Vikram Subramaniam", initials: "VS", avatarColor: "#1d4ed8", batch: "2016", type: "Research Grant", amount: "₹75,000", date: "2025-11-30", note: "Research infrastructure grant for the school science club." },
  { id: "CON-005", alumniName: "Divya Nair",   initials: "DN", avatarColor: "#db2777", batch: "2016", type: "Health Camp",   amount: "Services",  date: "2026-02-15", note: "Free cardiac screening camp for staff and students." },
  { id: "CON-006", alumniName: "Mohammed Ashraf", initials: "MA", avatarColor: "#0d9488", batch: "2018", type: "Scholarship Fund", amount: "₹50,000", date: "2026-04-10", note: "Supported two students for national-level science olympiad travel." },
  { id: "CON-007", alumniName: "Rohan George",  initials: "RG", avatarColor: "#dc2626", batch: "2017", type: "Sports Equipment", amount: "₹30,000", date: "2026-05-01", note: "Cricket kit and nets donated to school sports department." },
  { id: "CON-008", alumniName: "Sneha Thomas",   initials: "ST", avatarColor: "#7c2d12", batch: "2019", type: "Art Workshop",    amount: "Services",  date: "2026-05-10", note: "Free digital art and content creation masterclass for students." },
];

// ─── Gallery ──────────────────────────────────────────────────────────────────
const UNS = (id, w = 800, h = 600) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&h=${h}&q=85`;

export const MOCK_GALLERY = [
  {
    id: "GAL-001", title: "Annual Reunion 2025", type: "reunion", year: "2025", bg: "#1e3a5f", emoji: "🎉",
    img: UNS("1511578314322-379afb476865", 600, 450),
    photos: [
      UNS("1511578314322-379afb476865"), UNS("1540575467063-178a50c2df87"),
      UNS("1529156069898-49953e39b3ac"), UNS("1505373877841-8d25f7d46678"),
      UNS("1522202176988-66273c2fd55f"), UNS("1523580494863-6f3031224c94"),
    ],
  },
  {
    id: "GAL-002", title: "Tech Talk: AI Panel 2025", type: "webinar", year: "2025", bg: "#14532d", emoji: "💻",
    img: UNS("1540575467063-178a50c2df87", 600, 450),
    photos: [
      UNS("1540575467063-178a50c2df87"), UNS("1531482615713-2afd69097998"),
      UNS("1555255707-c07966088b7b"),    UNS("1509062522246-3755977927d7"),
      UNS("1543269865-cbf427effbad"),    UNS("1517245386807-bb43f82c33c4"),
    ],
  },
  {
    id: "GAL-003", title: "Sports Day Alumni 2025", type: "sports", year: "2025", bg: "#7c2d12", emoji: "🏆",
    img: UNS("1461896836934-ffe607ba8211", 600, 450),
    photos: [
      UNS("1461896836934-ffe607ba8211"), UNS("1540747913346-19212a4b7e14"),
      UNS("1574629810360-7efbbe195018"), UNS("1571019613454-1cb2f99b2d8b"),
      UNS("1517649281921-0a440123a4b6"), UNS("1505373877841-8d25f7d46678"),
    ],
  },
  {
    id: "GAL-004", title: "Batch 2022 Farewell", type: "memory", year: "2022", bg: "#4c1d95", emoji: "🎓",
    img: UNS("1523580494863-6f3031224c94", 600, 450),
    photos: [
      UNS("1523580494863-6f3031224c94"), UNS("1523050854058-8df90110c9f1"),
      UNS("1567532939604-b6b5b0db2604"), UNS("1524178232363-1fb2b075b655"),
      UNS("1522202176988-66273c2fd55f"), UNS("1511578314322-379afb476865"),
    ],
  },
  {
    id: "GAL-005", title: "IAS Felicitation Ceremony", type: "award", year: "2023", bg: "#78350f", emoji: "🏅",
    img: UNS("1585829365295-ab7cd400c167", 600, 450),
    photos: [
      UNS("1585829365295-ab7cd400c167"), UNS("1524178232363-1fb2b075b655"),
      UNS("1540575467063-178a50c2df87"), UNS("1517245386807-bb43f82c33c4"),
      UNS("1505373877841-8d25f7d46678"), UNS("1522202176988-66273c2fd55f"),
    ],
  },
  {
    id: "GAL-006", title: "Entrepreneurs Dinner 2025", type: "networking", year: "2025", bg: "#164e63", emoji: "🤝",
    img: UNS("1505373877841-8d25f7d46678", 600, 450),
    photos: [
      UNS("1505373877841-8d25f7d46678"), UNS("1529156069898-49953e39b3ac"),
      UNS("1511578314322-379afb476865"), UNS("1543269865-cbf427effbad"),
      UNS("1540575467063-178a50c2df87"), UNS("1522202176988-66273c2fd55f"),
    ],
  },
  {
    id: "GAL-007", title: "Alumni Homecoming 2024", type: "reunion", year: "2024", bg: "#1e3a5f", emoji: "🏫",
    img: UNS("1524492412937-b28074a5d7da", 600, 450),
    photos: [
      UNS("1524492412937-b28074a5d7da"), UNS("1511578314322-379afb476865"),
      UNS("1529156069898-49953e39b3ac"), UNS("1505373877841-8d25f7d46678"),
      UNS("1516450360452-9312f5e86fc7"), UNS("1523580494863-6f3031224c94"),
    ],
  },
  {
    id: "GAL-008", title: "STEM Career Fair 2024", type: "networking", year: "2024", bg: "#052e16", emoji: "🔬",
    img: UNS("1552664730-d307ca884978", 600, 450),
    photos: [
      UNS("1552664730-d307ca884978"), UNS("1540575467063-178a50c2df87"),
      UNS("1531482615713-2afd69097998"), UNS("1543269865-cbf427effbad"),
      UNS("1509062522246-3755977927d7"), UNS("1517245386807-bb43f82c33c4"),
    ],
  },
  {
    id: "GAL-009", title: "Batch 2021 Reunion", type: "reunion", year: "2021", bg: "#312e81", emoji: "📸",
    img: UNS("1529156069898-49953e39b3ac", 600, 450),
    photos: [
      UNS("1529156069898-49953e39b3ac"), UNS("1511578314322-379afb476865"),
      UNS("1505373877841-8d25f7d46678"), UNS("1523580494863-6f3031224c94"),
      UNS("1522202176988-66273c2fd55f"), UNS("1540575467063-178a50c2df87"),
    ],
  },
  {
    id: "GAL-010", title: "Cultural Fest Alumni Night", type: "memory", year: "2024", bg: "#4a044e", emoji: "🎭",
    img: UNS("1516450360452-9312f5e86fc7", 600, 450),
    photos: [
      UNS("1516450360452-9312f5e86fc7"), UNS("1523907289021-f19eded27520"),
      UNS("1511578314322-379afb476865"), UNS("1567532939604-b6b5b0db2604"),
      UNS("1540575467063-178a50c2df87"), UNS("1529156069898-49953e39b3ac"),
    ],
  },
  {
    id: "GAL-011", title: "Batch 2019 – 5 Year Reunion", type: "reunion", year: "2024", bg: "#1c1917", emoji: "🥂",
    img: UNS("1523580494863-6f3031224c94", 600, 450),
    photos: [
      UNS("1491438590572-5f3f33d86dae"), UNS("1529156069898-49953e39b3ac"),
      UNS("1511578314322-379afb476865"), UNS("1505373877841-8d25f7d46678"),
      UNS("1523580494863-6f3031224c94"), UNS("1516450360452-9312f5e86fc7"),
    ],
  },
  {
    id: "GAL-012", title: "Alumni Cricket Tournament 2025", type: "sports", year: "2025", bg: "#0c4a6e", emoji: "🏏",
    img: UNS("1531415074968-036ba1b575da", 600, 450),
    photos: [
      UNS("1531415074968-036ba1b575da"), UNS("1461896836934-ffe607ba8211"),
      UNS("1574629810360-7efbbe195018"), UNS("1571019613454-1cb2f99b2d8b"),
      UNS("1517649281921-0a440123a4b6"), UNS("1505373877841-8d25f7d46678"),
    ],
  },
];

// ─── Metrics helper ───────────────────────────────────────────────────────────
/**
 * Compute overview metrics from alumni list.
 * @param {Array} alumni
 * @returns {object}
 */
export const computeAlumniMetrics = (alumni, events, mentorshipReqs) => ({
  total:       alumni.length,
  verified:    alumni.filter(a => a.verificationStatus === "verified").length,
  mentors:     alumni.filter(a => a.isMentor && a.mentorStatus === "active").length,
  abroad:      alumni.filter(a => a.isAbroad).length,
  upcomingEvt: events.filter(e => e.status === "upcoming").length,
  pendingReqs: mentorshipReqs.filter(r => r.status === "pending").length,
});

export const ALUMNI_METRICS_DEF = [
  { id: "total",       label: "Total Alumni",              icon: "🎓", color: "primary"  },
  { id: "verified",    label: "Verified Alumni",           icon: "✅", color: "success"  },
  { id: "mentors",     label: "Active Mentors",            icon: "🧑‍🏫", color: "info"    },
  { id: "abroad",      label: "Alumni Abroad",             icon: "✈️", color: "neutral"  },
  { id: "upcomingEvt", label: "Upcoming Events",           icon: "📅", color: "warning"  },
  { id: "pendingReqs", label: "Pending Mentorship Reqs",   icon: "📬", color: "danger"   },
];

// ─── Filter options ───────────────────────────────────────────────────────────
export const VERIFICATION_FILTER_OPTIONS = [
  { value: "all",      label: "All Statuses"  },
  { value: "verified", label: "Verified"      },
  { value: "pending",  label: "Pending"       },
  { value: "rejected", label: "Rejected"      },
];

export const MENTOR_FILTER_OPTIONS = [
  { value: "all",  label: "All Alumni"         },
  { value: "yes",  label: "Mentors Only"       },
  { value: "no",   label: "Non-Mentors Only"   },
];

export const ABROAD_FILTER_OPTIONS = [
  { value: "all",    label: "All Locations" },
  { value: "abroad", label: "Abroad"        },
  { value: "local",  label: "In India"      },
];

export const EVENT_TYPE_OPTIONS = [
  { value: "all",        label: "All Types"    },
  { value: "reunion",    label: "Reunion"      },
  { value: "webinar",    label: "Webinar"      },
  { value: "networking", label: "Networking"   },
];

export const MENTOR_STATUS_OPTIONS = [
  { value: "all",      label: "All Requests" },
  { value: "pending",  label: "Pending"      },
  { value: "approved", label: "Approved"     },
  { value: "rejected", label: "Rejected"     },
];
