export const TEACHER_ROUTES = {
  OVERVIEW: '/teacher/overview',
  MEETING_SCHEDULES: '/teacher/meeting-schedules',
  RESOURCES_UPLOADING: '/teacher/resources-uploading',
  ASSIGNMENTS_EXAMS: '/teacher/assignments-exams',
  STUDENT_EVALUATIONS: '/teacher/student-evaluations',
  MY_CLASSES: '/teacher/my-classes',
  AI_ASSISTANT: '/teacher/ai-assistant',
  SPORTS: '/teacher/sports',
  STAFF_REQUESTS: '/teacher/staff-requests',
  COMMUNITY: '/teacher/community',
  GRIEVANCES: '/teacher/grievances',
  STAFF_CONNECT: '/teacher/staff-connect',
  ANNOUNCEMENTS: '/teacher/announcements',
  LEAVE_MANAGEMENT: '/teacher/leave-management',
  COMMUNICATION: '/teacher/communication',
  DAY_SCHEDULES: '/teacher/day-schedules',
  ATTENDANCE: '/teacher/attendance',
};

export const TEACHER_NAV_ITEMS = [
  { path: TEACHER_ROUTES.OVERVIEW, icon: '📊', label: 'Overview' },
  { path: TEACHER_ROUTES.MEETING_SCHEDULES, icon: '📅', label: 'Meeting Schedules' },
  { path: TEACHER_ROUTES.RESOURCES_UPLOADING, icon: '📤', label: 'Resources' },
  { path: TEACHER_ROUTES.ASSIGNMENTS_EXAMS, icon: '📝', label: 'Assignments & Exams' },
  { path: TEACHER_ROUTES.STUDENT_EVALUATIONS, icon: '⭐', label: 'Student Evaluations' },
  { path: TEACHER_ROUTES.MY_CLASSES, icon: '👥', label: 'My Classes' },
  { path: TEACHER_ROUTES.AI_ASSISTANT, icon: '🤖', label: 'AI Assistant' },
  { path: TEACHER_ROUTES.SPORTS, icon: '⚽', label: 'Sports' },
  { path: TEACHER_ROUTES.STAFF_REQUESTS, icon: '📋', label: 'Staff Requests' },
  { path: TEACHER_ROUTES.COMMUNITY, icon: '💬', label: 'Community' },
  { path: TEACHER_ROUTES.GRIEVANCES, icon: '📢', label: 'Grievances' },
  { path: TEACHER_ROUTES.STAFF_CONNECT, icon: '🤝', label: 'Staff Connect' },
  { path: TEACHER_ROUTES.ANNOUNCEMENTS, icon: '📣', label: 'Announcements' },
  { path: TEACHER_ROUTES.LEAVE_MANAGEMENT, icon: '🗓️', label: 'Leave Management' },
  { path: TEACHER_ROUTES.COMMUNICATION, icon: '💭', label: 'Communication' },
  { path: TEACHER_ROUTES.DAY_SCHEDULES, icon: '⏰', label: 'Day Schedules' },
  { path: TEACHER_ROUTES.ATTENDANCE, icon: '✅', label: 'Attendance' },
];

export const STATUS_COLORS = {
  pending: 'orange',
  approved: 'green',
  rejected: 'red',
  completed: 'green',
  scheduled: 'blue',
  active: 'green',
  inactive: 'gray',
};
