// --- Live Tracking Mock Data (lt-*) ---

// Status Constants
export const BUS_STATUSES = ['Moving', 'At Stop', 'Delayed', 'Maintenance', 'GPS Offline', 'Deviated', 'Completed'];
export const ALERT_SEVERITIES = ['Critical', 'High', 'Medium', 'Low'];
export const ALERT_TYPES = [
  'Overspeeding',
  'Route Deviation',
  'Delayed Arrival',
  'Long Stoppage',
  'Unauthorized Stop',
  'GPS Disconnected',
  'Emergency Alert',
];
export const ROUTE_OPTIONS = [
  { id: 'rt-1', label: 'Route 1 - South Zone' },
  { id: 'rt-2', label: 'Route 2 - West Zone' },
  { id: 'rt-3', label: 'Route 3 - North Zone' },
  { id: 'rt-4', label: 'Route 4 - East Zone' },
  { id: 'rt-5', label: 'Route 5 - Central Zone' },
];

// Mock Buses (10 buses with real-time data)
export const MOCK_LIVE_BUSES = [
  {
    id: 'bus-001',
    number: 'KA-01-AB-1234',
    route: 'Route 3 - North Zone',
    status: 'Moving',
    currentStop: 'Rajajinagar Stop',
    etaMinutes: 8,
    driver: 'Raju Singh',
    driverPhone: '+91-9876543210',
    driverExp: 12,
    driverLicenseExpiry: '2026-12-15',
    inCharge: 'Priya Sharma',
    cleaner: 'Vikram Reddy',
    occupancyCurrent: 42,
    occupancyCapacity: 45,
    speed: 45,
    gpsStatus: 'Online',
    lastUpdate: new Date(),
    location: { lat: 13.3479, lng: 74.7421, accuracy: 5 },
    routeProgress: [
      { id: 'stop-1', name: 'School Gate', time: '08:00 AM', completed: true, current: false },
      { id: 'stop-2', name: 'MG Road', time: '08:15 AM', completed: true, current: false },
      { id: 'stop-3', name: 'Rajajinagar Stop', time: '08:25 AM', completed: false, current: true },
      { id: 'stop-4', name: 'Cubbon Park', time: '08:35 AM', completed: false, current: false },
      { id: 'stop-5', name: 'Vidhana Soudha', time: '08:45 AM', completed: false, current: false },
      { id: 'stop-6', name: 'Terminus', time: '09:00 AM', completed: false, current: false },
    ],
    routeDistance: 12.5,
    alerts: [{ id: 'alt-001', severity: 'Low', type: 'Slight Delay', message: 'Traffic on MG Road' }],
    vehicleHealth: { fuelLevel: 75, engineTemp: 82, brakeStatus: 'Good', engineOil: 'Normal' },
    serviceHistory: [
      { date: '2026-05-10', type: 'Regular Service', cost: 3500, nextDue: '2026-08-10' },
      { date: '2026-04-01', type: 'Oil Change', cost: 1200, nextDue: '2026-07-01' },
    ],
  },
  {
    id: 'bus-002',
    number: 'KA-01-CD-5678',
    route: 'Route 5 - East Zone',
    status: 'At Stop',
    currentStop: 'HAL Airport Stop',
    etaMinutes: 0,
    driver: 'Mohan Das',
    driverPhone: '+91-9876543211',
    driverExp: 8,
    driverLicenseExpiry: '2027-06-20',
    inCharge: 'Anita Patel',
    cleaner: 'Suresh Kumar',
    occupancyCurrent: 38,
    occupancyCapacity: 45,
    speed: 0,
    gpsStatus: 'Online',
    lastUpdate: new Date(),
    location: { lat: 13.2011, lng: 77.7066, accuracy: 3 },
    routeProgress: [
      { id: 'stop-1', name: 'Airport Terminal', time: '08:10 AM', completed: true, current: false },
      { id: 'stop-2', name: 'Indira Nagar', time: '08:25 AM', completed: true, current: false },
      { id: 'stop-3', name: 'HAL Airport Stop', time: '08:40 AM', completed: false, current: true },
      { id: 'stop-4', name: 'Whitefield', time: '08:55 AM', completed: false, current: false },
    ],
    routeDistance: 18.2,
    alerts: [],
    vehicleHealth: { fuelLevel: 60, engineTemp: 79, brakeStatus: 'Good', engineOil: 'Normal' },
    serviceHistory: [
      { date: '2026-04-15', type: 'General Maintenance', cost: 4200, nextDue: '2026-07-15' },
    ],
  },
  {
    id: 'bus-003',
    number: 'KA-01-EF-9012',
    route: 'Route 1 - South Zone',
    status: 'Moving',
    currentStop: 'Silk Board Junction',
    etaMinutes: 12,
    driver: 'Suresh Kumar',
    driverPhone: '+91-9876543212',
    driverExp: 15,
    driverLicenseExpiry: '2025-09-10',
    inCharge: 'Rajesh Verma',
    cleaner: 'Karthik Nair',
    occupancyCurrent: 43,
    occupancyCapacity: 45,
    speed: 38,
    gpsStatus: 'Online',
    lastUpdate: new Date(),
    location: { lat: 13.0312, lng: 77.6245, accuracy: 4 },
    routeProgress: [
      { id: 'stop-1', name: 'School Premises', time: '08:00 AM', completed: true, current: false },
      { id: 'stop-2', name: 'Bannerghatta Main Road', time: '08:20 AM', completed: true, current: false },
      { id: 'stop-3', name: 'Silk Board Junction', time: '08:35 AM', completed: false, current: true },
      { id: 'stop-4', name: 'BTM Layout', time: '08:50 AM', completed: false, current: false },
    ],
    routeDistance: 15.8,
    alerts: [{ id: 'alt-002', severity: 'High', type: 'Route Deviation', message: 'Took alternative route due to construction' }],
    vehicleHealth: { fuelLevel: 85, engineTemp: 80, brakeStatus: 'Good', engineOil: 'Normal' },
    serviceHistory: [
      { date: '2026-05-01', type: 'Preventive Maintenance', cost: 3800, nextDue: '2026-08-01' },
    ],
  },
  {
    id: 'bus-004',
    number: 'KA-01-GH-3456',
    route: 'Route 2 - West Zone',
    status: 'Delayed',
    currentStop: 'Malleshwaram Circle',
    etaMinutes: 22,
    driver: 'Ramesh Iyer',
    driverPhone: '+91-9876543213',
    driverExp: 10,
    driverLicenseExpiry: '2026-03-25',
    inCharge: 'Neha Singh',
    cleaner: 'Ashok Reddy',
    occupancyCurrent: 40,
    occupancyCapacity: 45,
    speed: 25,
    gpsStatus: 'Online',
    lastUpdate: new Date(),
    location: { lat: 13.3372, lng: 77.5733, accuracy: 6 },
    routeProgress: [
      { id: 'stop-1', name: 'School Main Gate', time: '08:05 AM', completed: true, current: false },
      { id: 'stop-2', name: 'Commercial Street', time: '08:20 AM', completed: true, current: false },
      { id: 'stop-3', name: 'Malleshwaram Circle', time: '08:40 AM', completed: false, current: true },
      { id: 'stop-4', name: 'Sanjaynagar', time: '08:55 AM', completed: false, current: false },
    ],
    routeDistance: 14.3,
    alerts: [{ id: 'alt-003', severity: 'Critical', type: 'Delayed Arrival', message: 'Heavy traffic at peak hours' }],
    vehicleHealth: { fuelLevel: 50, engineTemp: 88, brakeStatus: 'Good', engineOil: 'Low' },
    serviceHistory: [
      { date: '2026-04-20', type: 'Oil Change & Filter', cost: 1500, nextDue: '2026-07-20' },
    ],
  },
  {
    id: 'bus-005',
    number: 'KA-01-IJ-7890',
    route: 'Route 4 - East Zone',
    status: 'GPS Offline',
    currentStop: 'Indiranagar 100 Feet Road',
    etaMinutes: null,
    driver: 'Praveen Kumar',
    driverPhone: '+91-9876543214',
    driverExp: 9,
    driverLicenseExpiry: '2026-11-30',
    inCharge: 'Deepa Roy',
    cleaner: 'Manoj Singh',
    occupancyCurrent: 35,
    occupancyCapacity: 45,
    speed: null,
    gpsStatus: 'Offline',
    lastUpdate: new Date(Date.now() - 8 * 60000),
    location: { lat: 13.3542, lng: 77.6397, accuracy: null },
    routeProgress: [
      { id: 'stop-1', name: 'City Center', time: '08:10 AM', completed: true, current: false },
      { id: 'stop-2', name: 'Indiranagar 100 Feet Road', time: '08:30 AM', completed: false, current: true },
      { id: 'stop-3', name: 'BTM Layout', time: '08:45 AM', completed: false, current: false },
    ],
    routeDistance: 11.5,
    alerts: [{ id: 'alt-004', severity: 'Critical', type: 'GPS Disconnected', message: 'GPS signal lost since 8:15 AM' }],
    vehicleHealth: { fuelLevel: 70, engineTemp: 82, brakeStatus: 'Good', engineOil: 'Normal' },
    serviceHistory: [
      { date: '2026-03-15', type: 'General Service', cost: 4000, nextDue: '2026-06-15' },
    ],
  },
  {
    id: 'bus-006',
    number: 'KA-01-KL-2345',
    route: 'Route 3 - North Zone',
    status: 'Moving',
    currentStop: 'Yeshwanthpur Station',
    etaMinutes: 5,
    driver: 'Sanjay Rao',
    driverPhone: '+91-9876543215',
    driverExp: 11,
    driverLicenseExpiry: '2025-12-05',
    inCharge: 'Pooja Singh',
    cleaner: 'Vishnu Kumar',
    occupancyCurrent: 44,
    occupancyCapacity: 45,
    speed: 52,
    gpsStatus: 'Online',
    lastUpdate: new Date(),
    location: { lat: 13.3711, lng: 77.5831, accuracy: 4 },
    routeProgress: [
      { id: 'stop-1', name: 'School Gate', time: '08:00 AM', completed: true, current: false },
      { id: 'stop-2', name: 'Vijayanagar', time: '08:15 AM', completed: true, current: false },
      { id: 'stop-3', name: 'Yeshwanthpur Station', time: '08:25 AM', completed: false, current: true },
      { id: 'stop-4', name: 'Rajajinagar', time: '08:35 AM', completed: false, current: false },
    ],
    routeDistance: 13.2,
    alerts: [],
    vehicleHealth: { fuelLevel: 80, engineTemp: 81, brakeStatus: 'Good', engineOil: 'Normal' },
    serviceHistory: [
      { date: '2026-05-05', type: 'Routine Maintenance', cost: 3600, nextDue: '2026-08-05' },
    ],
  },
  {
    id: 'bus-007',
    number: 'KA-01-MN-6789',
    route: 'Route 5 - Central Zone',
    status: 'Completed',
    currentStop: 'School Premises',
    etaMinutes: null,
    driver: 'Kiran Nair',
    driverPhone: '+91-9876543216',
    driverExp: 7,
    driverLicenseExpiry: '2027-08-15',
    inCharge: 'Sneha Gupta',
    cleaner: 'Ravi Shankar',
    occupancyCurrent: 0,
    occupancyCapacity: 45,
    speed: 0,
    gpsStatus: 'Online',
    lastUpdate: new Date(),
    location: { lat: 13.2298, lng: 77.6355, accuracy: 3 },
    routeProgress: [
      { id: 'stop-1', name: 'Starting Point', time: '08:00 AM', completed: true, current: false },
      { id: 'stop-2', name: 'Mid Route', time: '08:30 AM', completed: true, current: false },
      { id: 'stop-3', name: 'School Premises', time: '09:00 AM', completed: true, current: true },
    ],
    routeDistance: 16.4,
    alerts: [],
    vehicleHealth: { fuelLevel: 65, engineTemp: 75, brakeStatus: 'Good', engineOil: 'Normal' },
    serviceHistory: [
      { date: '2026-04-10', type: 'Regular Service', cost: 3400, nextDue: '2026-07-10' },
    ],
  },
  {
    id: 'bus-008',
    number: 'KA-01-OP-4567',
    route: 'Route 2 - West Zone',
    status: 'Maintenance',
    currentStop: 'Service Center',
    etaMinutes: null,
    driver: 'Anand Kumar',
    driverPhone: '+91-9876543217',
    driverExp: 13,
    driverLicenseExpiry: '2026-05-20',
    inCharge: 'Kavya Mishra',
    cleaner: 'Harish Patel',
    occupancyCurrent: 0,
    occupancyCapacity: 45,
    speed: 0,
    gpsStatus: 'Online',
    lastUpdate: new Date(),
    location: { lat: 13.1986, lng: 77.6956, accuracy: 5 },
    routeProgress: [],
    routeDistance: 0,
    alerts: [{ id: 'alt-005', severity: 'Medium', type: 'Under Maintenance', message: 'Engine service in progress' }],
    vehicleHealth: { fuelLevel: 40, engineTemp: 90, brakeStatus: 'Maintenance', engineOil: 'Low' },
    serviceHistory: [
      { date: '2026-05-20', type: 'Engine Overhaul', cost: 8500, nextDue: '2026-12-20' },
      { date: '2026-04-05', type: 'Brake Inspection', cost: 2200, nextDue: '2026-10-05' },
    ],
  },
  {
    id: 'bus-009',
    number: 'KA-01-QR-8901',
    route: 'Route 1 - South Zone',
    status: 'Moving',
    currentStop: 'Electronic City Phase 1',
    etaMinutes: 15,
    driver: 'Vinay Reddy',
    driverPhone: '+91-9876543218',
    driverExp: 6,
    driverLicenseExpiry: '2027-02-10',
    inCharge: 'Mithila Sharma',
    cleaner: 'Prakash Reddy',
    occupancyCurrent: 41,
    occupancyCapacity: 45,
    speed: 42,
    gpsStatus: 'Online',
    lastUpdate: new Date(),
    location: { lat: 12.9698, lng: 77.6787, accuracy: 4 },
    routeProgress: [
      { id: 'stop-1', name: 'School Gate', time: '08:00 AM', completed: true, current: false },
      { id: 'stop-2', name: 'HSR Layout', time: '08:20 AM', completed: true, current: false },
      { id: 'stop-3', name: 'Electronic City Phase 1', time: '08:35 AM', completed: false, current: true },
      { id: 'stop-4', name: 'Electronic City Phase 2', time: '08:50 AM', completed: false, current: false },
    ],
    routeDistance: 17.6,
    alerts: [{ id: 'alt-006', severity: 'Low', type: 'Speed Check', message: 'Approaching school zone' }],
    vehicleHealth: { fuelLevel: 92, engineTemp: 78, brakeStatus: 'Good', engineOil: 'Normal' },
    serviceHistory: [
      { date: '2026-05-12', type: 'Routine Service', cost: 3200, nextDue: '2026-08-12' },
    ],
  },
  {
    id: 'bus-010',
    number: 'KA-01-ST-2345',
    route: 'Route 4 - East Zone',
    status: 'Deviated',
    currentStop: 'Koramangala Block 4',
    etaMinutes: 18,
    driver: 'Harish Menon',
    driverPhone: '+91-9876543219',
    driverExp: 14,
    driverLicenseExpiry: '2026-07-05',
    inCharge: 'Isha Kapoor',
    cleaner: 'Sujit Kumar',
    occupancyCurrent: 39,
    occupancyCapacity: 45,
    speed: 35,
    gpsStatus: 'Online',
    lastUpdate: new Date(),
    location: { lat: 13.0350, lng: 77.6245, accuracy: 5 },
    routeProgress: [
      { id: 'stop-1', name: 'Origin', time: '08:00 AM', completed: true, current: false },
      { id: 'stop-2', name: 'Koramangala Block 4', time: '08:40 AM', completed: false, current: true },
      { id: 'stop-3', name: 'Jubilee Hills', time: '09:00 AM', completed: false, current: false },
    ],
    routeDistance: 14.9,
    alerts: [{ id: 'alt-007', severity: 'High', type: 'Route Deviation', message: 'Taken detour to avoid traffic' }],
    vehicleHealth: { fuelLevel: 58, engineTemp: 85, brakeStatus: 'Good', engineOil: 'Normal' },
    serviceHistory: [
      { date: '2026-04-28', type: 'Tire Replacement', cost: 5200, nextDue: '2027-04-28' },
    ],
  },
];

// Mock Alerts (20+ active and historical alerts)
export const MOCK_ALERTS = [
  {
    id: 'alt-001',
    busId: 'bus-001',
    type: 'Overspeeding',
    severity: 'High',
    timestamp: new Date(Date.now() - 5 * 60000),
    message: 'Bus exceeded 60 km/h in school zone',
    duration: '2 minutes',
    status: 'Resolved',
    actionTaken: 'Driver notified, speed reduced',
  },
  {
    id: 'alt-002',
    busId: 'bus-003',
    type: 'Route Deviation',
    severity: 'High',
    timestamp: new Date(Date.now() - 12 * 60000),
    message: 'Bus took alternative route due to road construction',
    duration: 'Ongoing',
    status: 'Active',
    actionTaken: 'Route manager notified, ETA updated',
  },
  {
    id: 'alt-003',
    busId: 'bus-004',
    type: 'Delayed Arrival',
    severity: 'Critical',
    timestamp: new Date(Date.now() - 22 * 60000),
    message: 'Bus running 20+ minutes late due to heavy traffic',
    duration: 'Ongoing',
    status: 'Active',
    actionTaken: 'Notified school and parents, ETA updated to 8:55 AM',
  },
  {
    id: 'alt-004',
    busId: 'bus-005',
    type: 'GPS Disconnected',
    severity: 'Critical',
    timestamp: new Date(Date.now() - 8 * 60000),
    message: 'GPS signal lost, location cannot be tracked',
    duration: '8 minutes',
    status: 'Active',
    actionTaken: 'Technician notified, GPS module diagnostic initiated',
  },
  {
    id: 'alt-005',
    busId: 'bus-008',
    type: 'Under Maintenance',
    severity: 'Medium',
    timestamp: new Date(Date.now() - 45 * 60000),
    message: 'Bus is under engine service at service center',
    duration: 'Ongoing',
    status: 'Active',
    actionTaken: 'Backup bus assigned to route, service ETA 12:00 PM',
  },
  {
    id: 'alt-006',
    busId: 'bus-001',
    type: 'Long Stoppage',
    severity: 'Medium',
    timestamp: new Date(Date.now() - 3 * 60000),
    message: 'Bus at stop for longer than scheduled (5+ minutes)',
    duration: '5 minutes',
    status: 'Resolved',
    actionTaken: 'Manual intervention, delay compensated',
  },
  {
    id: 'alt-007',
    busId: 'bus-010',
    type: 'Route Deviation',
    severity: 'High',
    timestamp: new Date(Date.now() - 18 * 60000),
    message: 'Bus deviated from scheduled route to avoid traffic jam',
    duration: '10 minutes',
    status: 'Active',
    actionTaken: 'Route manager informed, new ETA calculated',
  },
  {
    id: 'alt-008',
    busId: 'bus-002',
    type: 'Unauthorized Stop',
    severity: 'Medium',
    timestamp: new Date(Date.now() - 25 * 60000),
    message: 'Bus stopped at unscheduled location',
    duration: '3 minutes',
    status: 'Resolved',
    actionTaken: 'Driver verified stop, continued journey',
  },
  {
    id: 'alt-009',
    busId: 'bus-009',
    type: 'Low Fuel Alert',
    severity: 'Medium',
    timestamp: new Date(Date.now() - 30 * 60000),
    message: 'Fuel level below 25% - recommend refueling',
    duration: '15 minutes',
    status: 'Active',
    actionTaken: 'Driver scheduled for next fuel station',
  },
  {
    id: 'alt-010',
    busId: 'bus-006',
    type: 'Emergency Alert',
    severity: 'Critical',
    timestamp: new Date(Date.now() - 60 * 60000),
    message: 'Emergency button pressed by driver/monitor',
    duration: '2 minutes',
    status: 'Resolved',
    actionTaken: 'Police notified, incident investigated and resolved',
  },
  {
    id: 'alt-011',
    busId: 'bus-004',
    type: 'Speed Threshold Exceeded',
    severity: 'High',
    timestamp: new Date(Date.now() - 35 * 60000),
    message: 'Excessive speeding detected at 75 km/h',
    duration: '1 minute',
    status: 'Resolved',
    actionTaken: 'Warning issued to driver',
  },
];

// Mock Analytics (Weekly/Monthly/Term Data)
export const MOCK_ANALYTICS = {
  weekly: {
    onTimeRate: 92.5,
    totalDistanceCovered: 487.3,
    fuelEfficiency: 5.8,
    delayedTrips: 2,
    studentsTransported: 1243,
    driverPerformance: 88.5,
    routeEfficiency: 91.2,
    breakdownFrequency: 0,
  },
  monthly: {
    onTimeRate: 89.8,
    totalDistanceCovered: 1945.6,
    fuelEfficiency: 5.6,
    delayedTrips: 8,
    studentsTransported: 4928,
    driverPerformance: 87.3,
    routeEfficiency: 90.1,
    breakdownFrequency: 1,
  },
  termWise: {
    onTimeRate: 91.2,
    totalDistanceCovered: 5847.3,
    fuelEfficiency: 5.7,
    delayedTrips: 24,
    studentsTransported: 14784,
    driverPerformance: 88.9,
    routeEfficiency: 91.5,
    breakdownFrequency: 2,
  },
};

// Status Icon & Color Mapping
export const STATUS_ICON_MAP = {
  'Moving': 'check',
  'At Stop': 'circle',
  'Delayed': 'clock',
  'Maintenance': 'wrench',
  'GPS Offline': 'alert',
  'Deviated': 'arrow-up-right',
  'Completed': 'check',
};

export const ALERT_COLOR_MAP = {
  'Critical': { bg: 'rgba(220, 38, 38, 0.1)', color: '#dc2626', icon: 'x-circle' },
  'High': { bg: 'rgba(217, 119, 6, 0.1)', color: '#d97706', icon: 'alert-circle' },
  'Medium': { bg: 'rgba(37, 99, 235, 0.1)', color: '#2563eb', icon: 'alert' },
  'Low': { bg: 'rgba(107, 114, 128, 0.1)', color: '#6b7280', icon: 'info' },
};

export const ALERT_ICON_MAP = {
  'Overspeeding': 'wind',
  'Route Deviation': 'refresh-cw',
  'Delayed Arrival': 'clock',
  'Long Stoppage': 'stop-circle',
  'Unauthorized Stop': 'x-circle',
  'GPS Disconnected': 'wifi-off',
  'Emergency Alert': 'alert-triangle',
  'Low Fuel Alert': 'fuel',
  'Speed Threshold Exceeded': 'alert-circle',
  'Under Maintenance': 'wrench',
};

// Detail Tabs
export const DETAIL_TABS = ['Overview', 'Route', 'Stops', 'Driver', 'Alerts', 'History'];
