// ─── Routes & Drivers Mock Data ──────────────────────────────────────────────

// ── Configuration Constants ───────────────────────────────────────────────────
export const ROUTE_STATUSES = [
  { id: 'ACTIVE', label: 'Active', icon: '✓', color: '#16a34a' },
  { id: 'IDLE', label: 'Idle', icon: '⊘', color: '#f59e0b' },
  { id: 'BREAKDOWN', label: 'Breakdown', icon: '✕', color: '#dc2626' },
  { id: 'PLANNED', label: 'Planned', icon: '◑', color: '#2563eb' },
];

export const DRIVER_ROLES = [
  { id: 'DRIVER', label: 'Driver', icon: '🚗' },
  { id: 'BACKUP', label: 'Backup Driver', icon: '🚗' },
  { id: 'CLEANER', label: 'Cleaner', icon: '🧹' },
  { id: 'INCHARGE', label: 'In-Charge', icon: '👤' },
];

export const AC_TYPES = [
  { id: 'AC', label: 'AC', color: '#2563eb' },
  { id: 'NONAC', label: 'Non-AC', color: '#6b7280' },
];

export const OCCUPANCY_LEVELS = [
  { id: 'OK', label: 'OK', color: '#16a34a' },
  { id: 'HIGH', label: 'High', color: '#f59e0b' },
  { id: 'FULL', label: 'Full', color: '#dc2626' },
];

export const COMPLIANCE_ITEMS = [
  { id: 'FITNESS', label: 'Fitness Certificate' },
  { id: 'INSURANCE', label: 'Insurance' },
  { id: 'PERMIT', label: 'Road Permit' },
  { id: 'POLLUTION', label: 'Pollution Certificate' },
  { id: 'MAINTENANCE', label: 'Maintenance' },
];

export const DRIVER_STATUSES = [
  { id: 'ACTIVE', label: 'Active', color: '#16a34a' },
  { id: 'ON_LEAVE', label: 'On Leave', color: '#f59e0b' },
  { id: 'SUSPENDED', label: 'Suspended', color: '#dc2626' },
  { id: 'AVAILABLE', label: 'Available', color: '#2563eb' },
];

// ── Mock Drivers (25 total) ───────────────────────────────────────────────────
export const MOCK_DRIVERS = [
  {
    id: 'd1',
    name: 'Rajesh Kumar',
    role: 'DRIVER',
    license: 'KA-05-DL-20240315',
    licenseExpiry: '2025-03-15',
    phone: '+91-98765-43210',
    experience: 12,
    assignedRoute: 'r1',
    assignedBus: 'b1',
    status: 'ACTIVE',
    compliance: {
      FITNESS: { status: 'OK', expiry: '2025-06-30' },
      INSURANCE: { status: 'OK', expiry: '2025-12-31' },
      PERMIT: { status: 'OK', expiry: '2025-10-15' },
      POLLUTION: { status: 'OK', expiry: '2025-09-20' },
      MAINTENANCE: { status: 'OK', expiry: '2025-04-30' },
    },
    joinDate: '2012-01-15',
    salary: 25000,
  },
  {
    id: 'd2',
    name: 'Priya Singh',
    role: 'BACKUP',
    license: 'KA-05-DL-20230822',
    licenseExpiry: '2024-08-22',
    phone: '+91-98765-43211',
    experience: 8,
    assignedRoute: 'r1',
    assignedBus: 'b1',
    status: 'ACTIVE',
    compliance: {
      FITNESS: { status: 'EXPIRED', expiry: '2024-03-15' },
      INSURANCE: { status: 'OK', expiry: '2025-11-30' },
      PERMIT: { status: 'WARNING', expiry: '2025-02-20' },
      POLLUTION: { status: 'OK', expiry: '2025-08-10' },
      MAINTENANCE: { status: 'OK', expiry: '2025-03-30' },
    },
    joinDate: '2016-05-20',
    salary: 20000,
  },
  {
    id: 'd3',
    name: 'Mohammad Hassan',
    role: 'DRIVER',
    license: 'KA-05-DL-20241105',
    licenseExpiry: '2026-11-05',
    phone: '+91-98765-43212',
    experience: 15,
    assignedRoute: 'r2',
    assignedBus: 'b2',
    status: 'ACTIVE',
    compliance: {
      FITNESS: { status: 'OK', expiry: '2025-07-20' },
      INSURANCE: { status: 'OK', expiry: '2026-01-15' },
      PERMIT: { status: 'OK', expiry: '2025-11-30' },
      POLLUTION: { status: 'OK', expiry: '2025-10-05' },
      MAINTENANCE: { status: 'OK', expiry: '2025-05-15' },
    },
    joinDate: '2009-03-10',
    salary: 28000,
  },
  {
    id: 'd4',
    name: 'Anita Sharma',
    role: 'CLEANER',
    license: 'KA-05-DL-20230512',
    licenseExpiry: '2025-12-31',
    phone: '+91-98765-43213',
    experience: 5,
    assignedRoute: 'r2',
    assignedBus: 'b2',
    status: 'ACTIVE',
    compliance: {
      FITNESS: { status: 'WARNING', expiry: '2025-01-10' },
      INSURANCE: { status: 'OK', expiry: '2025-09-20' },
      PERMIT: { status: 'OK', expiry: '2025-08-30' },
      POLLUTION: { status: 'OK', expiry: '2025-07-15' },
      MAINTENANCE: { status: 'OK', expiry: '2025-02-28' },
    },
    joinDate: '2019-02-01',
    salary: 12000,
  },
  {
    id: 'd5',
    name: 'Vikram Patel',
    role: 'INCHARGE',
    license: 'KA-05-DL-20240728',
    licenseExpiry: '2026-07-28',
    phone: '+91-98765-43214',
    experience: 10,
    assignedRoute: 'r2',
    assignedBus: 'b2',
    status: 'ACTIVE',
    compliance: {
      FITNESS: { status: 'OK', expiry: '2025-09-10' },
      INSURANCE: { status: 'OK', expiry: '2025-12-31' },
      PERMIT: { status: 'OK', expiry: '2025-11-15' },
      POLLUTION: { status: 'OK', expiry: '2025-09-25' },
      MAINTENANCE: { status: 'OK', expiry: '2025-04-20' },
    },
    joinDate: '2014-06-15',
    salary: 22000,
  },
  {
    id: 'd6',
    name: 'Suresh Reddy',
    role: 'DRIVER',
    license: 'KA-05-DL-20231020',
    licenseExpiry: '2025-10-20',
    phone: '+91-98765-43215',
    experience: 7,
    assignedRoute: 'r3',
    assignedBus: 'b3',
    status: 'ON_LEAVE',
    compliance: {
      FITNESS: { status: 'OK', expiry: '2025-05-15' },
      INSURANCE: { status: 'WARNING', expiry: '2025-01-20' },
      PERMIT: { status: 'OK', expiry: '2025-12-10' },
      POLLUTION: { status: 'EXPIRED', expiry: '2024-10-30' },
      MAINTENANCE: { status: 'OK', expiry: '2025-06-15' },
    },
    joinDate: '2017-08-01',
    salary: 23000,
  },
  {
    id: 'd7',
    name: 'Deepika Nair',
    role: 'BACKUP',
    license: 'KA-05-DL-20240615',
    licenseExpiry: '2026-06-15',
    phone: '+91-98765-43216',
    experience: 6,
    assignedRoute: 'r3',
    assignedBus: 'b3',
    status: 'ACTIVE',
    compliance: {
      FITNESS: { status: 'OK', expiry: '2025-04-10' },
      INSURANCE: { status: 'OK', expiry: '2025-10-30' },
      PERMIT: { status: 'OK', expiry: '2025-09-20' },
      POLLUTION: { status: 'OK', expiry: '2025-08-05' },
      MAINTENANCE: { status: 'OK', expiry: '2025-03-25' },
    },
    joinDate: '2018-09-10',
    salary: 19000,
  },
  {
    id: 'd8',
    name: 'Arjun Verma',
    role: 'DRIVER',
    license: 'KA-05-DL-20241225',
    licenseExpiry: '2026-12-25',
    phone: '+91-98765-43217',
    experience: 11,
    assignedRoute: 'r4',
    assignedBus: 'b4',
    status: 'ACTIVE',
    compliance: {
      FITNESS: { status: 'OK', expiry: '2025-08-20' },
      INSURANCE: { status: 'OK', expiry: '2026-02-28' },
      PERMIT: { status: 'OK', expiry: '2025-12-15' },
      POLLUTION: { status: 'OK', expiry: '2025-11-10' },
      MAINTENANCE: { status: 'OK', expiry: '2025-05-30' },
    },
    joinDate: '2013-04-20',
    salary: 26000,
  },
  {
    id: 'd9',
    name: 'Sneha Desai',
    role: 'INCHARGE',
    license: 'KA-05-DL-20230911',
    licenseExpiry: '2025-09-11',
    phone: '+91-98765-43218',
    experience: 9,
    assignedRoute: 'r4',
    assignedBus: 'b4',
    status: 'ACTIVE',
    compliance: {
      FITNESS: { status: 'WARNING', expiry: '2025-02-05' },
      INSURANCE: { status: 'OK', expiry: '2025-11-15' },
      PERMIT: { status: 'OK', expiry: '2025-10-20' },
      POLLUTION: { status: 'OK', expiry: '2025-09-30' },
      MAINTENANCE: { status: 'OK', expiry: '2025-04-10' },
    },
    joinDate: '2015-07-25',
    salary: 21000,
  },
  {
    id: 'd10',
    name: 'Ramesh Gupta',
    role: 'CLEANER',
    license: 'KA-05-DL-20240403',
    licenseExpiry: '2026-04-03',
    phone: '+91-98765-43219',
    experience: 4,
    assignedRoute: 'r4',
    assignedBus: 'b4',
    status: 'ACTIVE',
    compliance: {
      FITNESS: { status: 'OK', expiry: '2025-06-15' },
      INSURANCE: { status: 'OK', expiry: '2025-12-10' },
      PERMIT: { status: 'OK', expiry: '2025-11-05' },
      POLLUTION: { status: 'OK', expiry: '2025-10-20' },
      MAINTENANCE: { status: 'OK', expiry: '2025-03-15' },
    },
    joinDate: '2020-01-10',
    salary: 11000,
  },
  {
    id: 'd11',
    name: 'Kavya Mishra',
    role: 'DRIVER',
    license: 'KA-05-DL-20240814',
    licenseExpiry: '2026-08-14',
    phone: '+91-98765-43220',
    experience: 8,
    assignedRoute: 'r5',
    assignedBus: 'b5',
    status: 'ACTIVE',
    compliance: {
      FITNESS: { status: 'OK', expiry: '2025-07-10' },
      INSURANCE: { status: 'OK', expiry: '2025-12-20' },
      PERMIT: { status: 'OK', expiry: '2025-11-25' },
      POLLUTION: { status: 'OK', expiry: '2025-10-15' },
      MAINTENANCE: { status: 'OK', expiry: '2025-04-25' },
    },
    joinDate: '2016-11-20',
    salary: 24000,
  },
  {
    id: 'd12',
    name: 'Ravi Teja',
    role: 'BACKUP',
    license: 'KA-05-DL-20231201',
    licenseExpiry: '2025-12-01',
    phone: '+91-98765-43221',
    experience: 6,
    assignedRoute: 'r5',
    assignedBus: 'b5',
    status: 'AVAILABLE',
    compliance: {
      FITNESS: { status: 'EXPIRED', expiry: '2024-11-30' },
      INSURANCE: { status: 'OK', expiry: '2025-10-05' },
      PERMIT: { status: 'WARNING', expiry: '2025-01-15' },
      POLLUTION: { status: 'OK', expiry: '2025-09-10' },
      MAINTENANCE: { status: 'OK', expiry: '2025-02-20' },
    },
    joinDate: '2018-03-15',
    salary: 18000,
  },
  {
    id: 'd13',
    name: 'Meera Kapoor',
    role: 'INCHARGE',
    license: 'KA-05-DL-20240506',
    licenseExpiry: '2026-05-06',
    phone: '+91-98765-43222',
    experience: 11,
    assignedRoute: 'r5',
    assignedBus: 'b5',
    status: 'ACTIVE',
    compliance: {
      FITNESS: { status: 'OK', expiry: '2025-08-30' },
      INSURANCE: { status: 'OK', expiry: '2026-01-10' },
      PERMIT: { status: 'OK', expiry: '2025-12-20' },
      POLLUTION: { status: 'OK', expiry: '2025-11-05' },
      MAINTENANCE: { status: 'OK', expiry: '2025-05-10' },
    },
    joinDate: '2013-02-01',
    salary: 23000,
  },
  {
    id: 'd14',
    name: 'Arun Singh',
    role: 'DRIVER',
    license: 'KA-05-DL-20240229',
    licenseExpiry: '2026-02-29',
    phone: '+91-98765-43223',
    experience: 9,
    assignedRoute: 'r6',
    assignedBus: 'b1',
    status: 'ACTIVE',
    compliance: {
      FITNESS: { status: 'OK', expiry: '2025-05-20' },
      INSURANCE: { status: 'OK', expiry: '2025-11-15' },
      PERMIT: { status: 'OK', expiry: '2025-10-10' },
      POLLUTION: { status: 'OK', expiry: '2025-09-15' },
      MAINTENANCE: { status: 'OK', expiry: '2025-03-20' },
    },
    joinDate: '2015-06-10',
    salary: 25000,
  },
  {
    id: 'd15',
    name: 'Pooja Das',
    role: 'CLEANER',
    license: 'KA-05-DL-20240717',
    licenseExpiry: '2026-07-17',
    phone: '+91-98765-43224',
    experience: 3,
    assignedRoute: 'r6',
    assignedBus: 'b1',
    status: 'ACTIVE',
    compliance: {
      FITNESS: { status: 'OK', expiry: '2025-04-05' },
      INSURANCE: { status: 'OK', expiry: '2025-10-25' },
      PERMIT: { status: 'OK', expiry: '2025-09-15' },
      POLLUTION: { status: 'OK', expiry: '2025-08-20' },
      MAINTENANCE: { status: 'OK', expiry: '2025-02-10' },
    },
    joinDate: '2021-05-01',
    salary: 10000,
  },
  {
    id: 'd16',
    name: 'Rohit Joshi',
    role: 'DRIVER',
    license: 'KA-05-DL-20231109',
    licenseExpiry: '2025-11-09',
    phone: '+91-98765-43225',
    experience: 13,
    assignedRoute: 'r7',
    assignedBus: 'b2',
    status: 'ACTIVE',
    compliance: {
      FITNESS: { status: 'OK', expiry: '2025-06-25' },
      INSURANCE: { status: 'OK', expiry: '2025-12-15' },
      PERMIT: { status: 'OK', expiry: '2025-11-20' },
      POLLUTION: { status: 'OK', expiry: '2025-10-25' },
      MAINTENANCE: { status: 'OK', expiry: '2025-04-15' },
    },
    joinDate: '2011-08-20',
    salary: 27000,
  },
  {
    id: 'd17',
    name: 'Divya Negi',
    role: 'BACKUP',
    license: 'KA-05-DL-20240312',
    licenseExpiry: '2026-03-12',
    phone: '+91-98765-43226',
    experience: 7,
    assignedRoute: 'r7',
    assignedBus: 'b2',
    status: 'ACTIVE',
    compliance: {
      FITNESS: { status: 'WARNING', expiry: '2025-01-25' },
      INSURANCE: { status: 'OK', expiry: '2025-09-30' },
      PERMIT: { status: 'OK', expiry: '2025-08-20' },
      POLLUTION: { status: 'OK', expiry: '2025-07-30' },
      MAINTENANCE: { status: 'OK', expiry: '2025-02-25' },
    },
    joinDate: '2017-10-05',
    salary: 20000,
  },
  {
    id: 'd18',
    name: 'Vishal Kumar',
    role: 'INCHARGE',
    license: 'KA-05-DL-20240125',
    licenseExpiry: '2026-01-25',
    phone: '+91-98765-43227',
    experience: 10,
    assignedRoute: 'r7',
    assignedBus: 'b2',
    status: 'ACTIVE',
    compliance: {
      FITNESS: { status: 'OK', expiry: '2025-07-15' },
      INSURANCE: { status: 'OK', expiry: '2026-01-05' },
      PERMIT: { status: 'OK', expiry: '2025-12-10' },
      POLLUTION: { status: 'OK', expiry: '2025-11-20' },
      MAINTENANCE: { status: 'OK', expiry: '2025-05-05' },
    },
    joinDate: '2014-09-01',
    salary: 22000,
  },
  {
    id: 'd19',
    name: 'Neha Rao',
    role: 'DRIVER',
    license: 'KA-05-DL-20230627',
    licenseExpiry: '2025-06-27',
    phone: '+91-98765-43228',
    experience: 5,
    assignedRoute: 'r8',
    assignedBus: 'b3',
    status: 'AVAILABLE',
    compliance: {
      FITNESS: { status: 'OK', expiry: '2025-03-20' },
      INSURANCE: { status: 'EXPIRED', expiry: '2024-08-10' },
      PERMIT: { status: 'OK', expiry: '2025-07-15' },
      POLLUTION: { status: 'WARNING', expiry: '2025-01-05' },
      MAINTENANCE: { status: 'OK', expiry: '2025-01-30' },
    },
    joinDate: '2019-11-10',
    salary: 21000,
  },
  {
    id: 'd20',
    name: 'Sanjay Yadav',
    role: 'CLEANER',
    license: 'KA-05-DL-20240819',
    licenseExpiry: '2026-08-19',
    phone: '+91-98765-43229',
    experience: 6,
    assignedRoute: 'r8',
    assignedBus: 'b3',
    status: 'ACTIVE',
    compliance: {
      FITNESS: { status: 'OK', expiry: '2025-05-10' },
      INSURANCE: { status: 'OK', expiry: '2025-11-20' },
      PERMIT: { status: 'OK', expiry: '2025-10-30' },
      POLLUTION: { status: 'OK', expiry: '2025-09-25' },
      MAINTENANCE: { status: 'OK', expiry: '2025-03-10' },
    },
    joinDate: '2018-12-15',
    salary: 12500,
  },
  {
    id: 'd21',
    name: 'Ritika Gupta',
    role: 'DRIVER',
    license: 'KA-05-DL-20240410',
    licenseExpiry: '2026-04-10',
    phone: '+91-98765-43230',
    experience: 8,
    assignedRoute: 'r9',
    assignedBus: 'b4',
    status: 'ACTIVE',
    compliance: {
      FITNESS: { status: 'OK', expiry: '2025-06-10' },
      INSURANCE: { status: 'OK', expiry: '2025-12-05' },
      PERMIT: { status: 'OK', expiry: '2025-11-10' },
      POLLUTION: { status: 'OK', expiry: '2025-10-05' },
      MAINTENANCE: { status: 'OK', expiry: '2025-04-05' },
    },
    joinDate: '2016-02-20',
    salary: 23000,
  },
  {
    id: 'd22',
    name: 'Manoj Bhat',
    role: 'BACKUP',
    license: 'KA-05-DL-20231016',
    licenseExpiry: '2025-10-16',
    phone: '+91-98765-43231',
    experience: 7,
    assignedRoute: 'r9',
    assignedBus: 'b4',
    status: 'SUSPENDED',
    compliance: {
      FITNESS: { status: 'EXPIRED', expiry: '2024-09-20' },
      INSURANCE: { status: 'WARNING', expiry: '2025-01-30' },
      PERMIT: { status: 'OK', expiry: '2025-08-15' },
      POLLUTION: { status: 'OK', expiry: '2025-07-25' },
      MAINTENANCE: { status: 'OK', expiry: '2025-01-15' },
    },
    joinDate: '2017-04-10',
    salary: 19000,
  },
  {
    id: 'd23',
    name: 'Sunita Pathak',
    role: 'INCHARGE',
    license: 'KA-05-DL-20240208',
    licenseExpiry: '2026-02-08',
    phone: '+91-98765-43232',
    experience: 12,
    assignedRoute: 'r9',
    assignedBus: 'b4',
    status: 'ACTIVE',
    compliance: {
      FITNESS: { status: 'OK', expiry: '2025-08-10' },
      INSURANCE: { status: 'OK', expiry: '2026-01-20' },
      PERMIT: { status: 'OK', expiry: '2025-12-15' },
      POLLUTION: { status: 'OK', expiry: '2025-11-30' },
      MAINTENANCE: { status: 'OK', expiry: '2025-05-20' },
    },
    joinDate: '2012-07-05',
    salary: 24000,
  },
  {
    id: 'd24',
    name: 'Gaurav Singh',
    role: 'DRIVER',
    license: 'KA-05-DL-20240621',
    licenseExpiry: '2026-06-21',
    phone: '+91-98765-43233',
    experience: 6,
    assignedRoute: 'r10',
    assignedBus: 'b5',
    status: 'ACTIVE',
    compliance: {
      FITNESS: { status: 'OK', expiry: '2025-04-15' },
      INSURANCE: { status: 'OK', expiry: '2025-10-20' },
      PERMIT: { status: 'OK', expiry: '2025-09-25' },
      POLLUTION: { status: 'OK', expiry: '2025-08-30' },
      MAINTENANCE: { status: 'OK', expiry: '2025-02-15' },
    },
    joinDate: '2018-05-10',
    salary: 22000,
  },
  {
    id: 'd25',
    name: 'Lakshmi Iyer',
    role: 'CLEANER',
    license: 'KA-05-DL-20240503',
    licenseExpiry: '2026-05-03',
    phone: '+91-98765-43234',
    experience: 4,
    assignedRoute: 'r10',
    assignedBus: 'b5',
    status: 'ACTIVE',
    compliance: {
      FITNESS: { status: 'WARNING', expiry: '2025-01-10' },
      INSURANCE: { status: 'OK', expiry: '2025-11-10' },
      PERMIT: { status: 'OK', expiry: '2025-10-15' },
      POLLUTION: { status: 'OK', expiry: '2025-09-20' },
      MAINTENANCE: { status: 'OK', expiry: '2025-03-05' },
    },
    joinDate: '2020-08-01',
    salary: 11000,
  },
];

// ── Mock Routes (10 total) ────────────────────────────────────────────────────
export const MOCK_ROUTES = [
  {
    id: 'r1',
    name: 'North Route',
    code: 'NR-001',
    status: 'ACTIVE',
    startTime: '07:00',
    endTime: '18:30',
    distance: 24.5,
    busesCount: 2,
    stopsCount: 8,
    driversCount: 2,
    totalStudents: 45,
    totalTeachers: 3,
    averageOccupancy: '75%',
    occupancyStatus: 'OK',
    acType: 'NONAC',
    createdBy: 'd1',
    area: 'North Delhi',
    priority: 'HIGH',
    buses: ['b1', 'b2'],
    stops: [
      {
        id: 's1-1',
        name: 'School Main Gate',
        type: 'SCHOOL',
        time: '07:00',
        sequence: 1,
        students: 0,
        teachers: 3,
      },
      {
        id: 's1-2',
        name: 'Civil Lines Junction',
        type: 'STOP',
        time: '07:15',
        sequence: 2,
        students: 8,
        teachers: 0,
      },
      {
        id: 's1-3',
        name: 'Shastri Nagar Market',
        type: 'STOP',
        time: '07:30',
        sequence: 3,
        students: 12,
        teachers: 0,
      },
      {
        id: 's1-4',
        name: 'ISBT Station',
        type: 'STOP',
        time: '07:50',
        sequence: 4,
        students: 10,
        teachers: 0,
      },
      {
        id: 's1-5',
        name: 'Kasturba Nagar',
        type: 'STOP',
        time: '08:15',
        sequence: 5,
        students: 7,
        teachers: 0,
      },
      {
        id: 's1-6',
        name: 'Kanpur Road',
        type: 'STOP',
        time: '08:35',
        sequence: 6,
        students: 5,
        teachers: 0,
      },
      {
        id: 's1-7',
        name: 'Motinagar Area',
        type: 'STOP',
        time: '08:50',
        sequence: 7,
        students: 3,
        teachers: 0,
      },
      {
        id: 's1-8',
        name: 'Zakhira Junction',
        type: 'STOP',
        time: '09:00',
        sequence: 8,
        students: 0,
        teachers: 0,
      },
    ],
    compliance: {
      FITNESS: { status: 'OK', expiry: '2025-06-30' },
      INSURANCE: { status: 'OK', expiry: '2025-12-31' },
      PERMIT: { status: 'OK', expiry: '2025-10-15' },
      POLLUTION: { status: 'OK', expiry: '2025-09-20' },
      MAINTENANCE: { status: 'OK', expiry: '2025-04-30' },
    },
    alerts: [
      { id: 'a1-1', type: 'MAINTENANCE_DUE', severity: 'LOW', message: 'Scheduled maintenance due in 15 days', resolved: false },
    ],
  },
  {
    id: 'r2',
    name: 'South Route',
    code: 'SR-002',
    status: 'ACTIVE',
    startTime: '07:15',
    endTime: '18:45',
    distance: 28.3,
    busesCount: 2,
    stopsCount: 9,
    driversCount: 3,
    totalStudents: 52,
    totalTeachers: 3,
    averageOccupancy: '82%',
    occupancyStatus: 'HIGH',
    acType: 'AC',
    createdBy: 'd3',
    area: 'South Delhi',
    priority: 'HIGH',
    buses: ['b2', 'b3'],
    stops: [
      {
        id: 's2-1',
        name: 'School Main Gate',
        type: 'SCHOOL',
        time: '07:15',
        sequence: 1,
        students: 0,
        teachers: 3,
      },
      {
        id: 's2-2',
        name: 'Green Park',
        type: 'STOP',
        time: '07:35',
        sequence: 2,
        students: 9,
        teachers: 0,
      },
      {
        id: 's2-3',
        name: 'Hauz Khas',
        type: 'STOP',
        time: '07:55',
        sequence: 3,
        students: 14,
        teachers: 0,
      },
      {
        id: 's2-4',
        name: 'Malviya Nagar',
        type: 'STOP',
        time: '08:20',
        sequence: 4,
        students: 11,
        teachers: 0,
      },
      {
        id: 's2-5',
        name: 'Greater Kailash',
        type: 'STOP',
        time: '08:45',
        sequence: 5,
        students: 8,
        teachers: 0,
      },
      {
        id: 's2-6',
        name: 'Kalkaji Extension',
        type: 'STOP',
        time: '09:10',
        sequence: 6,
        students: 6,
        teachers: 0,
      },
      {
        id: 's2-7',
        name: 'Bhikaji Cama Place',
        type: 'STOP',
        time: '09:25',
        sequence: 7,
        students: 3,
        teachers: 0,
      },
      {
        id: 's2-8',
        name: 'Chhatarpur',
        type: 'STOP',
        time: '09:40',
        sequence: 8,
        students: 1,
        teachers: 0,
      },
      {
        id: 's2-9',
        name: 'Route End',
        type: 'STOP',
        time: '09:50',
        sequence: 9,
        students: 0,
        teachers: 0,
      },
    ],
    compliance: {
      FITNESS: { status: 'WARNING', expiry: '2025-01-25' },
      INSURANCE: { status: 'OK', expiry: '2025-12-15' },
      PERMIT: { status: 'OK', expiry: '2025-11-20' },
      POLLUTION: { status: 'OK', expiry: '2025-10-30' },
      MAINTENANCE: { status: 'OK', expiry: '2025-05-15' },
    },
    alerts: [
      {
        id: 'a2-1',
        type: 'FITNESS_WARNING',
        severity: 'MEDIUM',
        message: 'Fitness certificate expiring in 30 days',
        resolved: false,
      },
    ],
  },
  {
    id: 'r3',
    name: 'East Route',
    code: 'ER-003',
    status: 'BREAKDOWN',
    startTime: '07:30',
    endTime: '19:00',
    distance: 31.2,
    busesCount: 2,
    stopsCount: 10,
    driversCount: 2,
    totalStudents: 48,
    totalTeachers: 2,
    averageOccupancy: '60%',
    occupancyStatus: 'OK',
    acType: 'NONAC',
    createdBy: 'd6',
    area: 'East Delhi',
    priority: 'MEDIUM',
    buses: ['b3', 'b4'],
    stops: [
      {
        id: 's3-1',
        name: 'School Main Gate',
        type: 'SCHOOL',
        time: '07:30',
        sequence: 1,
        students: 0,
        teachers: 2,
      },
      {
        id: 's3-2',
        name: 'Geeta Colony',
        type: 'STOP',
        time: '07:50',
        sequence: 2,
        students: 8,
        teachers: 0,
      },
      {
        id: 's3-3',
        name: 'Patparganj',
        type: 'STOP',
        time: '08:15',
        sequence: 3,
        students: 12,
        teachers: 0,
      },
      {
        id: 's3-4',
        name: 'Mayur Vihar Phase I',
        type: 'STOP',
        time: '08:40',
        sequence: 4,
        students: 9,
        teachers: 0,
      },
      {
        id: 's3-5',
        name: 'Mayur Vihar Phase II',
        type: 'STOP',
        time: '09:00',
        sequence: 5,
        students: 7,
        teachers: 0,
      },
      {
        id: 's3-6',
        name: 'Noida Sector 62',
        type: 'STOP',
        time: '09:25',
        sequence: 6,
        students: 5,
        teachers: 0,
      },
      {
        id: 's3-7',
        name: 'Noida Sector 63',
        type: 'STOP',
        time: '09:40',
        sequence: 7,
        students: 0,
        teachers: 0,
      },
      {
        id: 's3-8',
        name: 'Akshardham',
        type: 'STOP',
        time: '09:55',
        sequence: 8,
        students: 0,
        teachers: 0,
      },
      {
        id: 's3-9',
        name: 'Route End',
        type: 'STOP',
        time: '10:10',
        sequence: 9,
        students: 0,
        teachers: 0,
      },
    ],
    compliance: {
      FITNESS: { status: 'EXPIRED', expiry: '2024-10-30' },
      INSURANCE: { status: 'WARNING', expiry: '2025-01-20' },
      PERMIT: { status: 'OK', expiry: '2025-08-15' },
      POLLUTION: { status: 'EXPIRED', expiry: '2024-09-25' },
      MAINTENANCE: { status: 'EXPIRED', expiry: '2024-12-10' },
    },
    alerts: [
      { id: 'a3-1', type: 'ROUTE_BREAKDOWN', severity: 'CRITICAL', message: 'Bus breakdown - route suspended', resolved: false },
      {
        id: 'a3-2',
        type: 'COMPLIANCE_EXPIRED',
        severity: 'CRITICAL',
        message: 'Multiple compliance certificates expired',
        resolved: false,
      },
      {
        id: 'a3-3',
        type: 'POLLUTION_CERT_EXPIRED',
        severity: 'CRITICAL',
        message: 'Pollution certificate expired',
        resolved: false,
      },
    ],
  },
  {
    id: 'r4',
    name: 'West Route',
    code: 'WR-004',
    status: 'ACTIVE',
    startTime: '07:45',
    endTime: '19:15',
    distance: 26.8,
    busesCount: 2,
    stopsCount: 8,
    driversCount: 3,
    totalStudents: 50,
    totalTeachers: 2,
    averageOccupancy: '78%',
    occupancyStatus: 'HIGH',
    acType: 'AC',
    createdBy: 'd8',
    area: 'West Delhi',
    priority: 'HIGH',
    buses: ['b4', 'b5'],
    stops: [
      {
        id: 's4-1',
        name: 'School Main Gate',
        type: 'SCHOOL',
        time: '07:45',
        sequence: 1,
        students: 0,
        teachers: 2,
      },
      {
        id: 's4-2',
        name: 'Tilak Nagar',
        type: 'STOP',
        time: '08:05',
        sequence: 2,
        students: 10,
        teachers: 0,
      },
      {
        id: 's4-3',
        name: 'Rajouri Garden',
        type: 'STOP',
        time: '08:25',
        sequence: 3,
        students: 13,
        teachers: 0,
      },
      {
        id: 's4-4',
        name: 'Karol Bagh',
        type: 'STOP',
        time: '08:50',
        sequence: 4,
        students: 11,
        teachers: 0,
      },
      {
        id: 's4-5',
        name: 'Pusa Road',
        type: 'STOP',
        time: '09:10',
        sequence: 5,
        students: 9,
        teachers: 0,
      },
      {
        id: 's4-6',
        name: 'Moti Nagar',
        type: 'STOP',
        time: '09:25',
        sequence: 6,
        students: 5,
        teachers: 0,
      },
      {
        id: 's4-7',
        name: 'Sabzi Mandi',
        type: 'STOP',
        time: '09:40',
        sequence: 7,
        students: 2,
        teachers: 0,
      },
      {
        id: 's4-8',
        name: 'Route End',
        type: 'STOP',
        time: '09:50',
        sequence: 8,
        students: 0,
        teachers: 0,
      },
    ],
    compliance: {
      FITNESS: { status: 'OK', expiry: '2025-07-15' },
      INSURANCE: { status: 'OK', expiry: '2025-12-31' },
      PERMIT: { status: 'OK', expiry: '2025-11-15' },
      POLLUTION: { status: 'OK', expiry: '2025-10-25' },
      MAINTENANCE: { status: 'OK', expiry: '2025-05-10' },
    },
    alerts: [],
  },
  {
    id: 'r5',
    name: 'City Center Route',
    code: 'CC-005',
    status: 'ACTIVE',
    startTime: '08:00',
    endTime: '19:30',
    distance: 18.5,
    busesCount: 2,
    stopsCount: 7,
    driversCount: 3,
    totalStudents: 44,
    totalTeachers: 2,
    averageOccupancy: '70%',
    occupancyStatus: 'OK',
    acType: 'AC',
    createdBy: 'd11',
    area: 'Central Delhi',
    priority: 'HIGH',
    buses: ['b1', 'b5'],
    stops: [
      {
        id: 's5-1',
        name: 'School Main Gate',
        type: 'SCHOOL',
        time: '08:00',
        sequence: 1,
        students: 0,
        teachers: 2,
      },
      {
        id: 's5-2',
        name: 'Connaught Place',
        type: 'STOP',
        time: '08:20',
        sequence: 2,
        students: 9,
        teachers: 0,
      },
      {
        id: 's5-3',
        name: 'Delhi Gate',
        type: 'STOP',
        time: '08:40',
        sequence: 3,
        students: 11,
        teachers: 0,
      },
      {
        id: 's5-4',
        name: 'New Delhi Railway Station',
        type: 'STOP',
        time: '09:00',
        sequence: 4,
        students: 8,
        teachers: 0,
      },
      {
        id: 's5-5',
        name: 'Parliament Street',
        type: 'STOP',
        time: '09:15',
        sequence: 5,
        students: 10,
        teachers: 0,
      },
      {
        id: 's5-6',
        name: 'Lok Sabha Road',
        type: 'STOP',
        time: '09:30',
        sequence: 6,
        students: 6,
        teachers: 0,
      },
      {
        id: 's5-7',
        name: 'Route End',
        type: 'STOP',
        time: '09:45',
        sequence: 7,
        students: 0,
        teachers: 0,
      },
    ],
    compliance: {
      FITNESS: { status: 'OK', expiry: '2025-08-20' },
      INSURANCE: { status: 'OK', expiry: '2026-01-10' },
      PERMIT: { status: 'OK', expiry: '2025-12-20' },
      POLLUTION: { status: 'OK', expiry: '2025-11-05' },
      MAINTENANCE: { status: 'OK', expiry: '2025-05-10' },
    },
    alerts: [],
  },
  {
    id: 'r6',
    name: 'Suburb Route A',
    code: 'SA-006',
    status: 'ACTIVE',
    startTime: '06:45',
    endTime: '18:00',
    distance: 35.2,
    busesCount: 2,
    stopsCount: 11,
    driversCount: 2,
    totalStudents: 55,
    totalTeachers: 3,
    averageOccupancy: '85%',
    occupancyStatus: 'FULL',
    acType: 'NONAC',
    createdBy: 'd14',
    area: 'Suburbs',
    priority: 'MEDIUM',
    buses: ['b1', 'b2'],
    stops: [
      {
        id: 's6-1',
        name: 'School Main Gate',
        type: 'SCHOOL',
        time: '06:45',
        sequence: 1,
        students: 0,
        teachers: 3,
      },
      {
        id: 's6-2',
        name: 'Mehrauli',
        type: 'STOP',
        time: '07:15',
        sequence: 2,
        students: 8,
        teachers: 0,
      },
      {
        id: 's6-3',
        name: 'Chhatarpur Mandir',
        type: 'STOP',
        time: '07:45',
        sequence: 3,
        students: 11,
        teachers: 0,
      },
      {
        id: 's6-4',
        name: 'Lado Sarai',
        type: 'STOP',
        time: '08:10',
        sequence: 4,
        students: 9,
        teachers: 0,
      },
      {
        id: 's6-5',
        name: 'Vasant Kunj',
        type: 'STOP',
        time: '08:35',
        sequence: 5,
        students: 12,
        teachers: 0,
      },
      {
        id: 's6-6',
        name: 'Uttam Nagar',
        type: 'STOP',
        time: '09:00',
        sequence: 6,
        students: 7,
        teachers: 0,
      },
      {
        id: 's6-7',
        name: 'Naraina',
        type: 'STOP',
        time: '09:20',
        sequence: 7,
        students: 5,
        teachers: 0,
      },
      {
        id: 's6-8',
        name: 'Najafgarh',
        type: 'STOP',
        time: '09:40',
        sequence: 8,
        students: 3,
        teachers: 0,
      },
      {
        id: 's6-9',
        name: 'Dwarka Sector 1',
        type: 'STOP',
        time: '10:00',
        sequence: 9,
        students: 0,
        teachers: 0,
      },
    ],
    compliance: {
      FITNESS: { status: 'OK', expiry: '2025-06-25' },
      INSURANCE: { status: 'OK', expiry: '2025-12-15' },
      PERMIT: { status: 'OK', expiry: '2025-11-20' },
      POLLUTION: { status: 'OK', expiry: '2025-10-25' },
      MAINTENANCE: { status: 'WARNING', expiry: '2025-01-10' },
    },
    alerts: [
      {
        id: 'a6-1',
        type: 'MAINTENANCE_WARNING',
        severity: 'MEDIUM',
        message: 'Maintenance due in 10 days',
        resolved: false,
      },
    ],
  },
  {
    id: 'r7',
    name: 'Suburb Route B',
    code: 'SB-007',
    status: 'ACTIVE',
    startTime: '06:30',
    endTime: '17:45',
    distance: 38.5,
    busesCount: 2,
    stopsCount: 12,
    driversCount: 3,
    totalStudents: 58,
    totalTeachers: 3,
    averageOccupancy: '80%',
    occupancyStatus: 'HIGH',
    acType: 'AC',
    createdBy: 'd16',
    area: 'Suburbs',
    priority: 'MEDIUM',
    buses: ['b2', 'b3'],
    stops: [
      {
        id: 's7-1',
        name: 'School Main Gate',
        type: 'SCHOOL',
        time: '06:30',
        sequence: 1,
        students: 0,
        teachers: 3,
      },
      {
        id: 's7-2',
        name: 'Gurgaon Border',
        type: 'STOP',
        time: '07:10',
        sequence: 2,
        students: 7,
        teachers: 0,
      },
      {
        id: 's7-3',
        name: 'Golf Course Road',
        type: 'STOP',
        time: '07:40',
        sequence: 3,
        students: 10,
        teachers: 0,
      },
      {
        id: 's7-4',
        name: 'Sector 31 Gurgaon',
        type: 'STOP',
        time: '08:10',
        sequence: 4,
        students: 12,
        teachers: 0,
      },
      {
        id: 's7-5',
        name: 'Sector 50 Gurgaon',
        type: 'STOP',
        time: '08:40',
        sequence: 5,
        students: 11,
        teachers: 0,
      },
      {
        id: 's7-6',
        name: 'Cyber City',
        type: 'STOP',
        time: '09:10',
        sequence: 6,
        students: 8,
        teachers: 0,
      },
      {
        id: 's7-7',
        name: 'MG Road',
        type: 'STOP',
        time: '09:30',
        sequence: 7,
        students: 6,
        teachers: 0,
      },
      {
        id: 's7-8',
        name: 'HUDA City Centre',
        type: 'STOP',
        time: '09:50',
        sequence: 8,
        students: 4,
        teachers: 0,
      },
      {
        id: 's7-9',
        name: 'Route End',
        type: 'STOP',
        time: '10:05',
        sequence: 9,
        students: 0,
        teachers: 0,
      },
    ],
    compliance: {
      FITNESS: { status: 'WARNING', expiry: '2025-02-05' },
      INSURANCE: { status: 'OK', expiry: '2025-11-15' },
      PERMIT: { status: 'OK', expiry: '2025-10-20' },
      POLLUTION: { status: 'OK', expiry: '2025-09-30' },
      MAINTENANCE: { status: 'OK', expiry: '2025-04-10' },
    },
    alerts: [
      {
        id: 'a7-1',
        type: 'FITNESS_WARNING',
        severity: 'MEDIUM',
        message: 'Fitness certificate expiring in 25 days',
        resolved: false,
      },
    ],
  },
  {
    id: 'r8',
    name: 'Industrial Route',
    code: 'IR-008',
    status: 'ACTIVE',
    startTime: '07:00',
    endTime: '18:30',
    distance: 22.7,
    busesCount: 1,
    stopsCount: 6,
    driversCount: 2,
    totalStudents: 35,
    totalTeachers: 2,
    averageOccupancy: '65%',
    occupancyStatus: 'OK',
    acType: 'NONAC',
    createdBy: 'd19',
    area: 'Industrial Area',
    priority: 'LOW',
    buses: ['b3', 'b4'],
    stops: [
      {
        id: 's8-1',
        name: 'School Main Gate',
        type: 'SCHOOL',
        time: '07:00',
        sequence: 1,
        students: 0,
        teachers: 2,
      },
      {
        id: 's8-2',
        name: 'Okhla Phase I',
        type: 'STOP',
        time: '07:30',
        sequence: 2,
        students: 10,
        teachers: 0,
      },
      {
        id: 's8-3',
        name: 'Okhla Phase II',
        type: 'STOP',
        time: '07:55',
        sequence: 3,
        students: 12,
        teachers: 0,
      },
      {
        id: 's8-4',
        name: 'Okhla Phase III',
        type: 'STOP',
        time: '08:20',
        sequence: 4,
        students: 8,
        teachers: 0,
      },
      {
        id: 's8-5',
        name: 'Sukhdev Vihar',
        type: 'STOP',
        time: '08:40',
        sequence: 5,
        students: 5,
        teachers: 0,
      },
      {
        id: 's8-6',
        name: 'Route End',
        type: 'STOP',
        time: '08:55',
        sequence: 6,
        students: 0,
        teachers: 0,
      },
    ],
    compliance: {
      FITNESS: { status: 'OK', expiry: '2025-05-10' },
      INSURANCE: { status: 'EXPIRED', expiry: '2024-08-10' },
      PERMIT: { status: 'OK', expiry: '2025-07-15' },
      POLLUTION: { status: 'WARNING', expiry: '2025-01-05' },
      MAINTENANCE: { status: 'OK', expiry: '2025-01-30' },
    },
    alerts: [
      {
        id: 'a8-1',
        type: 'INSURANCE_EXPIRED',
        severity: 'CRITICAL',
        message: 'Insurance certificate expired',
        resolved: false,
      },
      {
        id: 'a8-2',
        type: 'POLLUTION_WARNING',
        severity: 'HIGH',
        message: 'Pollution certificate expiring soon',
        resolved: false,
      },
    ],
  },
  {
    id: 'r9',
    name: 'Residential Route',
    code: 'RR-009',
    status: 'PLANNED',
    startTime: '08:15',
    endTime: '19:45',
    distance: 20.5,
    busesCount: 1,
    stopsCount: 7,
    driversCount: 3,
    totalStudents: 40,
    totalTeachers: 2,
    averageOccupancy: '72%',
    occupancyStatus: 'OK',
    acType: 'AC',
    createdBy: 'd21',
    area: 'Residential',
    priority: 'MEDIUM',
    buses: ['b4', 'b5'],
    stops: [
      {
        id: 's9-1',
        name: 'School Main Gate',
        type: 'SCHOOL',
        time: '08:15',
        sequence: 1,
        students: 0,
        teachers: 2,
      },
      {
        id: 's9-2',
        name: 'R.K. Puram',
        type: 'STOP',
        time: '08:35',
        sequence: 2,
        students: 9,
        teachers: 0,
      },
      {
        id: 's9-3',
        name: 'Safdarjung Enclave',
        type: 'STOP',
        time: '08:55',
        sequence: 3,
        students: 11,
        teachers: 0,
      },
      {
        id: 's9-4',
        name: 'Defence Colony',
        type: 'STOP',
        time: '09:15',
        sequence: 4,
        students: 10,
        teachers: 0,
      },
      {
        id: 's9-5',
        name: 'Lodi Garden',
        type: 'STOP',
        time: '09:35',
        sequence: 5,
        students: 7,
        teachers: 0,
      },
      {
        id: 's9-6',
        name: 'Barapullah',
        type: 'STOP',
        time: '09:50',
        sequence: 6,
        students: 3,
        teachers: 0,
      },
      {
        id: 's9-7',
        name: 'Route End',
        type: 'STOP',
        time: '10:00',
        sequence: 7,
        students: 0,
        teachers: 0,
      },
    ],
    compliance: {
      FITNESS: { status: 'OK', expiry: '2025-06-10' },
      INSURANCE: { status: 'OK', expiry: '2025-12-05' },
      PERMIT: { status: 'OK', expiry: '2025-11-10' },
      POLLUTION: { status: 'OK', expiry: '2025-10-05' },
      MAINTENANCE: { status: 'OK', expiry: '2025-04-05' },
    },
    alerts: [],
  },
  {
    id: 'r10',
    name: 'Special Route',
    code: 'SP-010',
    status: 'ACTIVE',
    startTime: '07:30',
    endTime: '19:00',
    distance: 24.2,
    busesCount: 1,
    stopsCount: 8,
    driversCount: 2,
    totalStudents: 38,
    totalTeachers: 2,
    averageOccupancy: '68%',
    occupancyStatus: 'OK',
    acType: 'AC',
    createdBy: 'd24',
    area: 'Mixed',
    priority: 'MEDIUM',
    buses: ['b5'],
    stops: [
      {
        id: 's10-1',
        name: 'School Main Gate',
        type: 'SCHOOL',
        time: '07:30',
        sequence: 1,
        students: 0,
        teachers: 2,
      },
      {
        id: 's10-2',
        name: 'Vivek Vihar',
        type: 'STOP',
        time: '07:50',
        sequence: 2,
        students: 8,
        teachers: 0,
      },
      {
        id: 's10-3',
        name: 'Preet Vihar',
        type: 'STOP',
        time: '08:10',
        sequence: 3,
        students: 10,
        teachers: 0,
      },
      {
        id: 's10-4',
        name: 'Krishna Nagar',
        type: 'STOP',
        time: '08:30',
        sequence: 4,
        students: 9,
        teachers: 0,
      },
      {
        id: 's10-5',
        name: 'Sunder Nagar',
        type: 'STOP',
        time: '08:50',
        sequence: 5,
        students: 6,
        teachers: 0,
      },
      {
        id: 's10-6',
        name: 'Kiran Garden',
        type: 'STOP',
        time: '09:10',
        sequence: 6,
        students: 4,
        teachers: 0,
      },
      {
        id: 's10-7',
        name: 'Ramphal Chowk',
        type: 'STOP',
        time: '09:25',
        sequence: 7,
        students: 1,
        teachers: 0,
      },
      {
        id: 's10-8',
        name: 'Route End',
        type: 'STOP',
        time: '09:35',
        sequence: 8,
        students: 0,
        teachers: 0,
      },
    ],
    compliance: {
      FITNESS: { status: 'OK', expiry: '2025-04-15' },
      INSURANCE: { status: 'OK', expiry: '2025-10-20' },
      PERMIT: { status: 'OK', expiry: '2025-09-25' },
      POLLUTION: { status: 'OK', expiry: '2025-08-30' },
      MAINTENANCE: { status: 'OK', expiry: '2025-02-15' },
    },
    alerts: [],
  },
];

// ── Alert Definitions (sorted by severity) ────────────────────────────────────
export const ALERT_DEFINITIONS = [
  {
    id: 'ROUTE_BREAKDOWN',
    label: 'Route Breakdown',
    severity: 'CRITICAL',
    icon: '⚠️',
    description: 'Bus breakdown - route suspended',
  },
  {
    id: 'COMPLIANCE_EXPIRED',
    label: 'Compliance Expired',
    severity: 'CRITICAL',
    icon: '⛔',
    description: 'Multiple compliance certificates expired',
  },
  {
    id: 'INSURANCE_EXPIRED',
    label: 'Insurance Expired',
    severity: 'CRITICAL',
    icon: '🚫',
    description: 'Insurance certificate expired',
  },
  {
    id: 'POLLUTION_CERT_EXPIRED',
    label: 'Pollution Cert Expired',
    severity: 'CRITICAL',
    icon: '💨',
    description: 'Pollution certificate expired',
  },
  {
    id: 'FITNESS_WARNING',
    label: 'Fitness Warning',
    severity: 'MEDIUM',
    icon: '⚠️',
    description: 'Fitness certificate expiring soon',
  },
  {
    id: 'POLLUTION_WARNING',
    label: 'Pollution Warning',
    severity: 'HIGH',
    icon: '💨',
    description: 'Pollution certificate expiring soon',
  },
  {
    id: 'MAINTENANCE_WARNING',
    label: 'Maintenance Warning',
    severity: 'MEDIUM',
    icon: '🔧',
    description: 'Maintenance due soon',
  },
  {
    id: 'MAINTENANCE_DUE',
    label: 'Maintenance Due',
    severity: 'LOW',
    icon: '🔧',
    description: 'Scheduled maintenance',
  },
];