// ─── Policies Module — Mock Data ──────────────────────────────────────────────

export const POLICY_CATEGORIES = [
  { id: "academic",        label: "Academic",              icon: "📚", color: "#2563eb", bg: "rgba(37,99,235,.09)"    },
  { id: "attendance",      label: "Attendance",            icon: "✅", color: "#16a34a", bg: "rgba(22,163,74,.09)"    },
  { id: "examination",     label: "Examination",           icon: "📝", color: "#7c3aed", bg: "rgba(124,58,237,.09)"   },
  { id: "fee",             label: "Fee",                   icon: "💰", color: "#c9a962", bg: "rgba(201,169,98,.09)"   },
  { id: "transport",       label: "Transport",             icon: "🚌", color: "#0d9488", bg: "rgba(13,148,136,.09)"   },
  { id: "hostel",          label: "Hostel",                icon: "🏠", color: "#d97706", bg: "rgba(217,119,6,.09)"    },
  { id: "staff",           label: "Staff",                 icon: "👥", color: "#e11d48", bg: "rgba(225,29,72,.09)"    },
  { id: "student-conduct", label: "Student Conduct",       icon: "🎓", color: "#6d28d9", bg: "rgba(109,40,217,.09)"   },
  { id: "it-usage",        label: "IT & Internet",         icon: "💻", color: "#0369a1", bg: "rgba(3,105,161,.09)"    },
  { id: "safety",          label: "Safety & Security",     icon: "🔒", color: "#b91c1c", bg: "rgba(185,28,28,.09)"    },
  { id: "leave",           label: "Leave",                 icon: "📅", color: "#059669", bg: "rgba(5,150,105,.09)"    },
  { id: "grievance",       label: "Grievance",             icon: "⚖️",  color: "#dc2626", bg: "rgba(220,38,38,.09)"    },
  { id: "anti-ragging",    label: "Anti-Ragging",          icon: "🚫", color: "#7f1d1d", bg: "rgba(127,29,29,.09)"    },
  { id: "privacy",         label: "Privacy & Data",        icon: "🛡️",  color: "#1d4ed8", bg: "rgba(29,78,216,.09)"    },
  { id: "library",         label: "Library",               icon: "📖", color: "#92400e", bg: "rgba(146,64,14,.09)"    },
  { id: "discipline",      label: "Discipline",            icon: "📋", color: "#374151", bg: "rgba(55,65,81,.09)"     },
  { id: "events",          label: "Events",                icon: "🎪", color: "#9333ea", bg: "rgba(147,51,234,.09)"   },
  { id: "campus-rules",    label: "Campus Rules",          icon: "🏫", color: "#065f46", bg: "rgba(6,95,70,.09)"      },
  { id: "emergency",       label: "Emergency",             icon: "🚨", color: "#991b1b", bg: "rgba(153,27,27,.09)"    },
];

export const VISIBILITY_OPTIONS = [
  { value: "students",   label: "Students"   },
  { value: "teachers",   label: "Teachers"   },
  { value: "parents",    label: "Parents"    },
  { value: "staff",      label: "Staff"      },
  { value: "management", label: "Management" },
  { value: "all",        label: "All Users"  },
];

export const POLICY_STATUSES = [
  { value: "active",   label: "Active",   color: "#16a34a", bg: "rgba(22,163,74,.1)"   },
  { value: "draft",    label: "Draft",    color: "#d97706", bg: "rgba(217,119,6,.1)"   },
  { value: "archived", label: "Archived", color: "#6b7280", bg: "rgba(107,114,128,.1)" },
  { value: "expired",  label: "Expired",  color: "#dc2626", bg: "rgba(220,38,38,.1)"   },
];

export const APPROVAL_STAGES = ["Draft", "Under Review", "Approved", "Published"];

export const POLICY_METRICS_DEF = [
  { id: "total",    icon: "📄", label: "Total Policies",          color: "primary" },
  { id: "active",   icon: "✅", label: "Active Policies",         color: "success" },
  { id: "draft",    icon: "✏️",  label: "Draft Policies",          color: "warning" },
  { id: "archived", icon: "🗄️",  label: "Archived Policies",       color: "neutral" },
  { id: "pending",  icon: "⏳", label: "Pending Acknowledgments", color: "danger"  },
  { id: "updated",  icon: "🔄", label: "Recently Updated",        color: "info"    },
];

/**
 * Compute dashboard metrics from a policies array.
 * @param {Array} policies
 * @returns {object}
 */
export const computePolicyMetrics = (policies) => ({
  total:    policies.length,
  active:   policies.filter((p) => p.status === "active").length,
  draft:    policies.filter((p) => p.status === "draft").length,
  archived: policies.filter((p) => p.status === "archived").length,
  pending:  policies.reduce((sum, p) => sum + (p.ackPending || 0), 0),
  updated:  policies.filter((p) => {
    if (!p.lastUpdated) return false;
    return Date.now() - new Date(p.lastUpdated).getTime() < 30 * 24 * 60 * 60 * 1000;
  }).length,
});

// ── Date helpers ──────────────────────────────────────────────────────────────
const BASE = "2026-05-21";
const dAgo = (n) => {
  const d = new Date(BASE);
  d.setDate(d.getDate() - n);
  return d.toISOString().slice(0, 10);
};

// ── Mock Policies ─────────────────────────────────────────────────────────────
export const MOCK_POLICIES = [
  {
    id: "POL-0001",
    title: "Student Academic Integrity Policy",
    category: "academic",
    description: "Standards for academic honesty, plagiarism prevention, and ethical scholarly conduct.",
    content: "All students are expected to maintain the highest standards of academic integrity. Plagiarism, copying, or using unauthorized assistance in any academic work is strictly prohibited. AI-generated content submitted as original work is treated as academic dishonesty. Violations may result in grade penalties, suspension, or expulsion depending on severity.",
    version: "v3.2",
    effectiveDate: "2026-01-01",
    expiryDate: "2026-12-31",
    lastUpdated: dAgo(5),
    updatedBy: "Dr. Priya Nair",
    visibility: ["students", "teachers", "management"],
    status: "active",
    approvalStage: "Published",
    ackRequired: true,
    ackTotal: 420,
    ackDone: 389,
    ackPending: 31,
    attachments: [{ name: "Academic_Integrity_v3.2.pdf", type: "pdf", size: "420 KB" }],
    tags: ["integrity", "plagiarism", "academic"],
  },
  {
    id: "POL-0002",
    title: "Student Attendance Policy",
    category: "attendance",
    description: "Minimum attendance requirements and leave of absence procedures.",
    content: "Students must maintain a minimum of 75% attendance in all subjects to be eligible for examinations. Medical absences must be supported by a certified medical certificate. Prolonged absence without intimation will result in disciplinary action.",
    version: "v2.1",
    effectiveDate: "2026-01-01",
    expiryDate: "2026-12-31",
    lastUpdated: dAgo(12),
    updatedBy: "Karthik Menon",
    visibility: ["students", "parents", "teachers"],
    status: "active",
    approvalStage: "Published",
    ackRequired: true,
    ackTotal: 420,
    ackDone: 310,
    ackPending: 110,
    attachments: [{ name: "Attendance_Policy_v2.1.pdf", type: "pdf", size: "185 KB" }],
    tags: ["attendance", "leave", "absence"],
  },
  {
    id: "POL-0003",
    title: "Examination Conduct & Malpractice Policy",
    category: "examination",
    description: "Rules for examination conduct, invigilation, and disciplinary action for malpractice.",
    content: "Candidates must carry valid hall tickets and ID to all examinations. Use of mobile phones, electronic devices, or any unauthorized material during exams is strictly prohibited. Malpractice will result in cancellation of the examination and further disciplinary action.",
    version: "v4.0",
    effectiveDate: "2026-01-01",
    expiryDate: "2026-12-31",
    lastUpdated: dAgo(20),
    updatedBy: "Arjun Sharma",
    visibility: ["students", "teachers", "management"],
    status: "active",
    approvalStage: "Published",
    ackRequired: true,
    ackTotal: 420,
    ackDone: 402,
    ackPending: 18,
    attachments: [{ name: "Exam_Conduct_Policy_v4.0.pdf", type: "pdf", size: "310 KB" }],
    tags: ["exam", "malpractice", "conduct"],
  },
  {
    id: "POL-0004",
    title: "Fee Payment & Refund Policy",
    category: "fee",
    description: "Schedule of fee payments, late fee penalties, and refund procedures.",
    content: "All fees must be paid by the scheduled due dates. Late payment attracts a penalty of 2% per month. Refund requests must be submitted within 30 days of withdrawal. Refund eligibility depends on the stage of academic year at withdrawal.",
    version: "v2.3",
    effectiveDate: "2026-04-01",
    expiryDate: "2027-03-31",
    lastUpdated: dAgo(45),
    updatedBy: "Ravi Kumar",
    visibility: ["students", "parents", "management"],
    status: "active",
    approvalStage: "Published",
    ackRequired: false,
    ackTotal: 0,
    ackDone: 0,
    ackPending: 0,
    attachments: [
      { name: "Fee_Policy_v2.3.pdf", type: "pdf", size: "225 KB" },
      { name: "Fee_Schedule_2026.xlsx", type: "doc", size: "88 KB" },
    ],
    tags: ["fee", "payment", "refund"],
  },
  {
    id: "POL-0005",
    title: "School Transport Safety Policy",
    category: "transport",
    description: "Safety norms, route allocation, and conduct expectations for school transport.",
    content: "All students using school transport must carry their ID cards. Rowdy behavior in buses will result in cancellation of transport privilege. Students must be at the bus stop 5 minutes before the scheduled time. Parents are responsible for ensuring safe boarding and de-boarding.",
    version: "v1.5",
    effectiveDate: "2026-01-01",
    expiryDate: "2026-12-31",
    lastUpdated: dAgo(60),
    updatedBy: "Mohammed Faisal",
    visibility: ["students", "parents"],
    status: "active",
    approvalStage: "Published",
    ackRequired: true,
    ackTotal: 215,
    ackDone: 198,
    ackPending: 17,
    attachments: [{ name: "Transport_Safety_Policy.pdf", type: "pdf", size: "195 KB" }],
    tags: ["transport", "safety", "bus"],
  },
  {
    id: "POL-0006",
    title: "Hostel Rules & Regulations",
    category: "hostel",
    description: "Residential hostel guidelines including curfew, visitor, and disciplinary rules.",
    content: "Hostel inmates must adhere to curfew timings. Visitors are permitted only in designated areas and during approved hours. Students must maintain cleanliness in rooms and common areas. Ragging in any form is grounds for immediate expulsion from the hostel.",
    version: "v2.0",
    effectiveDate: "2026-06-01",
    expiryDate: "2027-05-31",
    lastUpdated: dAgo(3),
    updatedBy: "Anita George",
    visibility: ["students"],
    status: "draft",
    approvalStage: "Under Review",
    ackRequired: true,
    ackTotal: 0,
    ackDone: 0,
    ackPending: 0,
    attachments: [],
    tags: ["hostel", "residential", "rules"],
  },
  {
    id: "POL-0007",
    title: "Staff Code of Conduct",
    category: "staff",
    description: "Professional conduct standards expected from all teaching and non-teaching staff.",
    content: "All staff members are expected to maintain decorum and professionalism at all times. Punctuality, respectful communication, and adherence to institutional values are mandatory. Disclosure of confidential student or institutional information to unauthorized parties is strictly prohibited.",
    version: "v3.1",
    effectiveDate: "2026-01-01",
    expiryDate: "2026-12-31",
    lastUpdated: dAgo(90),
    updatedBy: "Priya Nair",
    visibility: ["staff", "management"],
    status: "active",
    approvalStage: "Published",
    ackRequired: true,
    ackTotal: 85,
    ackDone: 82,
    ackPending: 3,
    attachments: [{ name: "Staff_CoC_v3.1.pdf", type: "pdf", size: "290 KB" }],
    tags: ["staff", "conduct", "professional"],
  },
  {
    id: "POL-0008",
    title: "Student Conduct & Discipline Policy",
    category: "student-conduct",
    description: "Behavioral expectations, disciplinary procedures, and rights of students.",
    content: "Students must respect all faculty, staff, and fellow students. Bullying, harassment, or use of abusive language is strictly prohibited. Disciplinary proceedings follow a structured escalation process ensuring due process and right of appeal for the accused student.",
    version: "v2.5",
    effectiveDate: "2026-01-01",
    expiryDate: "2026-12-31",
    lastUpdated: dAgo(30),
    updatedBy: "Karthik Menon",
    visibility: ["students", "parents", "teachers"],
    status: "active",
    approvalStage: "Published",
    ackRequired: true,
    ackTotal: 420,
    ackDone: 350,
    ackPending: 70,
    attachments: [{ name: "Student_Conduct_v2.5.pdf", type: "pdf", size: "340 KB" }],
    tags: ["discipline", "conduct", "behavior"],
  },
  {
    id: "POL-0009",
    title: "IT & Internet Usage Policy",
    category: "it-usage",
    description: "Acceptable use of school IT infrastructure, internet, and digital devices.",
    content: "School computers and internet access must be used solely for academic and administrative purposes. Accessing inappropriate websites, social media for personal use, or downloading unauthorized software is prohibited. All activity on school networks is monitored and logged.",
    version: "v1.8",
    effectiveDate: "2026-01-01",
    expiryDate: "2026-12-31",
    lastUpdated: dAgo(75),
    updatedBy: "Vinod Babu",
    visibility: ["students", "staff", "teachers"],
    status: "active",
    approvalStage: "Published",
    ackRequired: true,
    ackTotal: 500,
    ackDone: 470,
    ackPending: 30,
    attachments: [{ name: "IT_Usage_Policy_v1.8.pdf", type: "pdf", size: "215 KB" }],
    tags: ["it", "internet", "digital"],
  },
  {
    id: "POL-0010",
    title: "Campus Safety & Security Policy",
    category: "safety",
    description: "Safety protocols, emergency procedures, and campus security guidelines.",
    content: "All visitors must register at the security desk and wear visitor badges at all times. CCTV surveillance is active across the campus. Students and staff must cooperate fully with security personnel. Reporting suspicious activity to security is mandatory.",
    version: "v3.0",
    effectiveDate: "2026-01-01",
    expiryDate: "2026-12-31",
    lastUpdated: dAgo(15),
    updatedBy: "Arjun Sharma",
    visibility: ["all"],
    status: "active",
    approvalStage: "Published",
    ackRequired: false,
    ackTotal: 0,
    ackDone: 0,
    ackPending: 0,
    attachments: [{ name: "Safety_Policy_v3.0.pdf", type: "pdf", size: "480 KB" }],
    tags: ["safety", "security", "emergency"],
  },
  {
    id: "POL-0011",
    title: "Staff Leave Policy",
    category: "leave",
    description: "Leave entitlements, application procedures, and approval workflows for staff.",
    content: "Teaching staff are entitled to 12 casual leaves and 15 medical leaves per academic year. Non-teaching staff are entitled to 10 casual leaves and 10 medical leaves. Leave must be applied for in advance except in emergencies. Carry-forward of casual leave is permitted up to a maximum of 5 days.",
    version: "v2.2",
    effectiveDate: "2026-01-01",
    expiryDate: "2026-12-31",
    lastUpdated: dAgo(120),
    updatedBy: "Anita George",
    visibility: ["staff", "management"],
    status: "active",
    approvalStage: "Published",
    ackRequired: true,
    ackTotal: 85,
    ackDone: 85,
    ackPending: 0,
    attachments: [{ name: "Leave_Policy_v2.2.pdf", type: "pdf", size: "165 KB" }],
    tags: ["leave", "staff", "entitlement"],
  },
  {
    id: "POL-0012",
    title: "Anti-Ragging Policy",
    category: "anti-ragging",
    description: "Zero-tolerance anti-ragging policy in compliance with UGC regulations.",
    content: "Ragging in any form — verbal, physical, mental, or cyber — is strictly prohibited. All students and parents must sign the anti-ragging declaration on admission. Complaints can be lodged with the Anti-Ragging Committee or the toll-free helpline. Offenders face immediate suspension and legal action.",
    version: "v5.0",
    effectiveDate: "2026-01-01",
    expiryDate: "2026-12-31",
    lastUpdated: dAgo(180),
    updatedBy: "Priya Nair",
    visibility: ["students", "parents", "teachers", "management"],
    status: "active",
    approvalStage: "Published",
    ackRequired: true,
    ackTotal: 420,
    ackDone: 416,
    ackPending: 4,
    attachments: [{ name: "Anti_Ragging_Policy_v5.0.pdf", type: "pdf", size: "225 KB" }],
    tags: ["anti-ragging", "safety", "compliance"],
  },
  {
    id: "POL-0013",
    title: "Data Privacy & Protection Policy",
    category: "privacy",
    description: "How student and staff data is collected, stored, processed, and protected.",
    content: "The institution collects personal data only for legitimate academic and administrative purposes. Data is not shared with third parties without explicit consent. Students and staff have the right to access, correct, or request deletion of their personal data. Data breaches must be reported within 72 hours.",
    version: "v1.3",
    effectiveDate: "2026-06-01",
    expiryDate: "2027-05-31",
    lastUpdated: dAgo(2),
    updatedBy: "Vinod Babu",
    visibility: ["all"],
    status: "draft",
    approvalStage: "Draft",
    ackRequired: false,
    ackTotal: 0,
    ackDone: 0,
    ackPending: 0,
    attachments: [],
    tags: ["privacy", "data", "gdpr"],
  },
  {
    id: "POL-0014",
    title: "Library Usage Policy",
    category: "library",
    description: "Rules for borrowing, returning, and using library resources.",
    content: "Students may borrow up to 3 books for a period of 14 days. Overdue books attract a fine of ₹2 per day per book. Damaged or lost books must be replaced at cost plus a 20% administrative charge. Silence must be maintained in the library at all times.",
    version: "v1.4",
    effectiveDate: "2025-01-01",
    expiryDate: "2025-12-31",
    lastUpdated: dAgo(95),
    updatedBy: "Latha Sundar",
    visibility: ["students", "staff"],
    status: "archived",
    approvalStage: "Approved",
    ackRequired: false,
    ackTotal: 0,
    ackDone: 0,
    ackPending: 0,
    attachments: [{ name: "Library_Policy_v1.4.pdf", type: "pdf", size: "120 KB" }],
    tags: ["library", "books", "borrowing"],
  },
  {
    id: "POL-0015",
    title: "Emergency Response & Evacuation Policy",
    category: "emergency",
    description: "Procedures for fire drills, medical emergencies, and campus evacuation.",
    content: "All staff and students must be familiar with designated evacuation routes. Fire drills are conducted twice per academic year. In the event of a medical emergency, trained first-aid staff must be notified immediately. Assembly points are marked at the main ground and parking area.",
    version: "v2.1",
    effectiveDate: "2026-01-01",
    expiryDate: "2026-12-31",
    lastUpdated: dAgo(8),
    updatedBy: "Arjun Sharma",
    visibility: ["all"],
    status: "active",
    approvalStage: "Published",
    ackRequired: true,
    ackTotal: 505,
    ackDone: 460,
    ackPending: 45,
    attachments: [{ name: "Emergency_Policy_v2.1.pdf", type: "pdf", size: "350 KB" }],
    tags: ["emergency", "evacuation", "safety"],
  },
  {
    id: "POL-0016",
    title: "Event Participation & Permission Policy",
    category: "events",
    description: "Rules for student participation in inter-school and off-campus events.",
    content: "Students wishing to participate in external events must submit a signed permission form from parents at least 5 working days prior. The institution bears no responsibility for injuries or losses during unauthorized participation. Participation in events must not interfere with academic commitments.",
    version: "v1.1",
    effectiveDate: "2026-01-01",
    expiryDate: "2026-12-31",
    lastUpdated: dAgo(55),
    updatedBy: "Divya Krishnan",
    visibility: ["students", "parents", "teachers"],
    status: "active",
    approvalStage: "Published",
    ackRequired: false,
    ackTotal: 0,
    ackDone: 0,
    ackPending: 0,
    attachments: [],
    tags: ["events", "participation", "permission"],
  },
  {
    id: "POL-0017",
    title: "Campus Rules & Regulations",
    category: "campus-rules",
    description: "General campus rules covering dress code, cleanliness, and movement.",
    content: "Students must wear the prescribed school uniform on all working days. Mobile phones are not permitted in classrooms. Movement between buildings during class hours requires a gate pass. Campus cleanliness is a shared responsibility — littering will attract fines.",
    version: "v3.3",
    effectiveDate: "2026-01-01",
    expiryDate: "2026-12-31",
    lastUpdated: dAgo(25),
    updatedBy: "Karthik Menon",
    visibility: ["students", "parents", "staff"],
    status: "active",
    approvalStage: "Published",
    ackRequired: true,
    ackTotal: 420,
    ackDone: 395,
    ackPending: 25,
    attachments: [{ name: "Campus_Rules_v3.3.pdf", type: "pdf", size: "275 KB" }],
    tags: ["campus", "uniform", "rules"],
  },
  {
    id: "POL-0018",
    title: "Grievance Redressal Policy",
    category: "grievance",
    description: "Process for filing, reviewing, and resolving student and staff grievances.",
    content: "Grievances may be submitted to the designated Grievance Redressal Committee via written application or the online portal. All grievances will be acknowledged within 3 working days and resolved within 21 working days. Anonymous complaints may be lodged but must provide sufficient detail for investigation.",
    version: "v1.6",
    effectiveDate: "2026-01-01",
    expiryDate: "2026-12-31",
    lastUpdated: dAgo(40),
    updatedBy: "Priya Nair",
    visibility: ["students", "staff", "management"],
    status: "active",
    approvalStage: "Published",
    ackRequired: false,
    ackTotal: 0,
    ackDone: 0,
    ackPending: 0,
    attachments: [{ name: "Grievance_Policy_v1.6.pdf", type: "pdf", size: "195 KB" }],
    tags: ["grievance", "redressal", "complaint"],
  },
  {
    id: "POL-0019",
    title: "Scholarship Eligibility & Disbursement Policy",
    category: "fee",
    description: "Criteria, application process, and disbursement rules for scholarships.",
    content: "Merit scholarships are available to students with 90%+ in the previous academic year. Need-based scholarships require submission of income proof and bank statements. Scholarship funds are disbursed directly to the fee account. Recipients must maintain eligibility criteria throughout the award period.",
    version: "v2.0",
    effectiveDate: "2026-04-01",
    expiryDate: "2027-03-31",
    lastUpdated: dAgo(1),
    updatedBy: "Ravi Kumar",
    visibility: ["students", "parents", "management"],
    status: "draft",
    approvalStage: "Under Review",
    ackRequired: false,
    ackTotal: 0,
    ackDone: 0,
    ackPending: 0,
    attachments: [],
    tags: ["scholarship", "fee", "eligibility"],
  },
  {
    id: "POL-0020",
    title: "Discipline & Suspension Policy",
    category: "discipline",
    description: "Escalation matrix and procedures for student disciplinary actions.",
    content: "Disciplinary action is proportional to the nature and severity of the offence. Minor infractions are handled at class teacher level. Serious misconduct is referred to the Discipline Committee. Suspension beyond 3 days requires Principal approval. A formal inquiry must precede any expulsion decision.",
    version: "v3.0",
    effectiveDate: "2025-01-01",
    expiryDate: "2025-12-31",
    lastUpdated: dAgo(70),
    updatedBy: "Karthik Menon",
    visibility: ["students", "parents", "teachers", "management"],
    status: "archived",
    approvalStage: "Approved",
    ackRequired: false,
    ackTotal: 0,
    ackDone: 0,
    ackPending: 0,
    attachments: [{ name: "Discipline_Policy_v3.0.pdf", type: "pdf", size: "305 KB" }],
    tags: ["discipline", "suspension", "escalation"],
  },
];

// ── Version History ───────────────────────────────────────────────────────────
export const MOCK_VERSIONS = {
  "POL-0001": [
    { version: "v3.2", date: dAgo(5),   by: "Dr. Priya Nair", summary: "Updated plagiarism section, added AI tools clause." },
    { version: "v3.1", date: dAgo(120), by: "Arjun Sharma",   summary: "Minor wording updates to section 4." },
    { version: "v3.0", date: dAgo(365), by: "Priya Nair",     summary: "Major revision — restructured for clarity." },
    { version: "v2.4", date: dAgo(730), by: "Priya Nair",     summary: "Added online submission rules." },
  ],
  "POL-0002": [
    { version: "v2.1", date: dAgo(12),  by: "Karthik Menon", summary: "Added medical leave attestation requirements." },
    { version: "v2.0", date: dAgo(200), by: "Priya Nair",    summary: "Complete rewrite for new academic year." },
    { version: "v1.5", date: dAgo(400), by: "Priya Nair",    summary: "Initial release with UGC compliance." },
  ],
  "POL-0007": [
    { version: "v3.1", date: dAgo(90),  by: "Priya Nair",   summary: "Added social media usage clause." },
    { version: "v3.0", date: dAgo(300), by: "Arjun Sharma", summary: "Restructured for readability." },
  ],
};

// ── Filter Options ────────────────────────────────────────────────────────────
export const CATEGORY_FILTER_OPTIONS = [
  { value: "all", label: "All Categories" },
  ...POLICY_CATEGORIES.map((c) => ({ value: c.id, label: c.label })),
];

export const STATUS_FILTER_OPTIONS = [
  { value: "all",      label: "All Status" },
  { value: "active",   label: "Active"     },
  { value: "draft",    label: "Draft"      },
  { value: "archived", label: "Archived"   },
  { value: "expired",  label: "Expired"    },
];

export const VISIBILITY_FILTER_OPTIONS = [
  { value: "all",        label: "All Audiences" },
  { value: "students",   label: "Students"      },
  { value: "teachers",   label: "Teachers"      },
  { value: "parents",    label: "Parents"       },
  { value: "staff",      label: "Staff"         },
  { value: "management", label: "Management"    },
];

export const ACK_FILTER_OPTIONS = [
  { value: "all",      label: "All"               },
  { value: "required", label: "Ack Required"      },
  { value: "pending",  label: "Has Pending Acks"  },
  { value: "complete", label: "Fully Acknowledged" },
];
